// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-sigma/sigma/pkg/infra/workq (interfaces: Producer,ProducerFactory,ConsumerFactory)
//
// Generated by this command:
//
//	mockgen -destination=workq_mocks.go -package=workq github.com/go-sigma/sigma/pkg/infra/workq Producer,ProducerFactory,ConsumerFactory
//

// Package workq is a generated GoMock package.
package workq

import (
	context "context"
	reflect "reflect"

	enums "github.com/go-sigma/sigma/pkg/api/enums"
	gomock "go.uber.org/mock/gomock"
)

// MockProducer is a mock of Producer interface.
type MockProducer struct {
	ctrl     *gomock.Controller
	recorder *MockProducerMockRecorder
	isgomock struct{}
}

// MockProducerMockRecorder is the mock recorder for MockProducer.
type MockProducerMockRecorder struct {
	mock *MockProducer
}

// NewMockProducer creates a new mock instance.
func NewMockProducer(ctrl *gomock.Controller) *MockProducer {
	mock := &MockProducer{ctrl: ctrl}
	mock.recorder = &MockProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducer) EXPECT() *MockProducerMockRecorder {
	return m.recorder
}

// Produce mocks base method.
func (m *MockProducer) Produce(ctx context.Context, topic enums.Daemon, payload any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, topic, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockProducerMockRecorder) Produce(ctx, topic, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockProducer)(nil).Produce), ctx, topic, payload)
}

// MockProducerFactory is a mock of ProducerFactory interface.
type MockProducerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockProducerFactoryMockRecorder
	isgomock struct{}
}

// MockProducerFactoryMockRecorder is the mock recorder for MockProducerFactory.
type MockProducerFactoryMockRecorder struct {
	mock *MockProducerFactory
}

// NewMockProducerFactory creates a new mock instance.
func NewMockProducerFactory(ctrl *gomock.Controller) *MockProducerFactory {
	mock := &MockProducerFactory{ctrl: ctrl}
	mock.recorder = &MockProducerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducerFactory) EXPECT() *MockProducerFactoryMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockProducerFactory) New(params ProducerParams) (Producer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", params)
	ret0, _ := ret[0].(Producer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockProducerFactoryMockRecorder) New(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockProducerFactory)(nil).New), params)
}

// MockConsumerFactory is a mock of ConsumerFactory interface.
type MockConsumerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerFactoryMockRecorder
	isgomock struct{}
}

// MockConsumerFactoryMockRecorder is the mock recorder for MockConsumerFactory.
type MockConsumerFactoryMockRecorder struct {
	mock *MockConsumerFactory
}

// NewMockConsumerFactory creates a new mock instance.
func NewMockConsumerFactory(ctrl *gomock.Controller) *MockConsumerFactory {
	mock := &MockConsumerFactory{ctrl: ctrl}
	mock.recorder = &MockConsumerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumerFactory) EXPECT() *MockConsumerFactoryMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockConsumerFactory) New(params ConsumerParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockConsumerFactoryMockRecorder) New(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockConsumerFactory)(nil).New), params)
}
