apiVersion: v2
name: sigma
description: Sigma is a painless self-hosted all in one OCI artifact manager service.
type: application
version: 0.1.0
appVersion: "1.3.0"
icon: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyBpZD0iYSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTAgMTkwIj4KICA8Y2lyY2xlIGN4PSI5NSIgY3k9Ijk1IiByPSI5NSIgc3R5bGU9ImZpbGw6ICNmOTlkMWM7Ii8+CiAgPGNpcmNsZSBjeD0iOTUiIGN5PSI5NSIgcj0iODUiIHN0eWxlPSJmaWxsOiAjY2Q0YjI3OyIvPgogIDxjaXJjbGUgY3g9Ijk1IiBjeT0iOTUiIHI9Ijc1IiBzdHlsZT0iZmlsbDogIzVjMmUwZTsiLz4KICA8cGF0aCBkPSJtNzEuMzIsMTI1Ljg4di01LjI4bDIzLjUyLTI5LjA5djQuOTlsLTIyLjU2LTMxLjU4di0zLjM2aDcuMDFsMjEuNiwzMC4yNC0yMy43MSwyOS45NS0yLjUtMy41NWgzOS41NWwtNS4yOCw0LjgsMy42NS0xNy4yOGg1Ljc2bC0uNzcsMjAuMTZoLTQ2LjI3Wm0zNi02NC4zMmw1LjI4LDQuOGgtMzcuMDV2LTQuOGg0MC40MWwuNzcsMTcuMDloLTUuNzZsLTMuNjUtMTcuMDlaIiBzdHlsZT0iZmlsbDogI2Y5OWQxYzsiLz4KPC9zdmc+

dependencies:
  - name: redis
    version: 20.1.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: minio
    version: 14.7.8
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: mysql
    version: 11.1.16
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
