# Default values for sigma.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: docker.io
  repository: go-sigma/sigma
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

middleware:
  type: internal

config:
  log:
    level: debug
  database:
    # The database type to use. Supported types are: sqlite3, mysql, postgresql
    type: mysql
    sqlite3:
      path: sigma.db
    mysql:
      host: 10.37.48.71
      port: 30306
      user: sigma
      password: sigma
      dbname: sigma
    postgresql:
      host: localhost
      port: 5432
      user: sigma
      password: sigma
      dbname: sigma
      sslmode: disable
  redis:
    url: redis://:sigma@10.37.48.71:30060/0
  http:
    server: 0.0.0.0:3000
    worker: 0.0.0.0:3001
  storage:
    rootdirectory: ./storage
    type: s3
    filesystem:
      path: /
    s3:
      ak: sigma
      sk: sigma-sigma
      endpoint: http://10.37.48.71:32000
      region: cn-north-1
      bucket: sigma
      forcePathStyle: true
  # Notice: the tag never update after the first pulled from remote registry, unless you delete the image and pull again.
  proxy:
    enabled: true
    endpoint: https://registry-1.docker.io
    tlsVerify: true
    username: ""
    password: ""
  auth:
    user:
      password: ""
    internalUser:
      username: internal-sigma
      password: internal-sigma
    admin:
      username: sigma
      password: sigma
    token:
      realm: ""
      service: ""
    jwt:
      ttl: 1h
      refreshTtl: 24h
      privateKey: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlTS1FJQkFBS0NCQUVBMUJNZE1pSDFsUHJNbWlYQ0xobXphRlloOTdMRU5nQUR5a2FzUDl3OU9rTlBYNGs4CmtuL3Y2eFliQU8yNTFMc0hpem9IVnNjckxpK2RjRCtBSXF4K2xHZ3Q0dE13ZkdaT2FmNVVBZ1g2b01UNHNJQnMKeGlpQWdIb2xpZlBNa2lHbG9mMDNPYnBGNmRIZzk4cWdsdy9vaHpQZDdhTlBoOGRVN2I4aTFoWG4wVXdJcktacQpZSnQxbk9BYnJUTUlNeWNTSVF4M01tcFlodzl6VERIZlB5K0VjOVl5Z1Z1eDZzOEx4MFlzMC9JN3BkK3NhcXExCm9iS3lrQ3FOdWhxOUoxS0drY0ZCMGJhOEpUL0ZHeFI4TDN2bFRkRGp4Z3QzVFdETm9wS3ptRU8zRndDM25yNnkKd3A5bmNoTG5LaS8wT0t0aGNiNVp6Mk9KNkllRWpFMG5uMmgzWVdPa0RNcG0rSll0bHQyTjJkUk5BdjFuYUttUApRMjVDRFlhcGVSajg4RkdMdVRWbmMvOURyTnJkejY2ckZBTGhkOENLQnBYWXowTkc5RG5zUThkWTlJSi9wK3hFCnl5Tjd0SWtvSWZUZ2lraFRqeEYzdWJVR3A1dHBPVWJLYUVXK1RERnZtZmIwdEx5NDlmZ2xuTnkxVHZTWjMyOFgKdEc2Tm1xNG1aV1NpUVh4MFkrdzUwZ0xic1dCbFBBR2xkSnI4OHdRMnliSUYrUVYwdjJWL0duRHkvb2xBN1BVQwpmL1hlVG9SUXMwRFA3SlJSVkFrZ3dsaWljVWFZRTAzMDJqd0VwclcwTGZZNTV1VFFiSXRYcmZKUmVmdDVoajNmCjhuQTlDUDZwVkVWRlNoV09xZkRXZFR2MWZ0bkVJNDRWK1BYbWh0MXUwTDVPM0VsYUV4L1FkSjJjQWtZQ3RRVkcKdW0vWTJRUllHbjBsb0FteHAwMEVQNTcxY210ejB0aVFlZWJ4L0krVFJrSHhoLzBCdVBmNWpWNGYwTWNGR3dBZAordEhSNU1YV3pXSkY1REtPYWZKLzdBaTIrR2ZMREsxU2t1MzlpQ1VXNUJJVjJGTjBtcWgwQkg3VVVIb1VUZVo2Cm01dHlZUHBMOGdtWnFJdVlBYWdqcXJhRzZKWnBuNXNCOHVwZnIvdCtqdm4xSjV1SzNzalVhQ21wTk1uSE5xdHoKZjRtUEtLZEhRQ3hBRURmbFZCWVV0U1hDTWhvUG1WWE5NSjVBYWxnb0ltZzFlN05ESTh5Y2NkaUN5RzZCOTNsWgpvYnByZElJTjEvMzJhVllkeW14dkh2eUlsTDdpQ2poZE9QMkNZbXYyTmRJN1dTRTRGUFdMWkZheWk4N0sxOCs5CllQR2VpSzA4MHdjdXZWc3BxVmxEZFVKRWhnemNFWFBBdDMzQVFyQXdSUzZsMTczaUwxRzRGcXQ5cGl0R3BLelMKRW9pVUJ5ZzYxVE1KbjRmam96TFc4U3hyWkwreEYwdUVUaUNvN2cvUDRjNEUzelkzOElodnp4eTB1eEx4emNMYQpHbDlFNEFEaU5CMm5icGhZV3IwQmpwYlJkalJ4Vld0eXdjdUd4c1kxb3RhMVI5UmNSSjA4U0kzdXc2VW9nb01sCnB0dnlLTktMeEVnWXNjRlY4U3dIc0hVMjRqK1RjcENlYk13WGs1ZUNHdDY5OVZNUEt3TENVcTBPcUpWT1JQZjMKSU9TYUhSMzNqd2FjMkhiWFpPVXhPS1RXS0g4QXFuSkdTTWM5UFNFcHBHVVRhSTFmaERQVjNlVktOK3djZElNSQpGRVA3RzJXbm1aN2RmVmlGT0kwL1BjbG9WRGNFdmhabmJ6ZElmUUlEQVFBQkFvSUVBRGRkS2hFTlpvUlhHUlRnCjZKbUtZaGpKNjZJempCK2d6MXgrS0xlZk1takVhN05BSzR6L1UwM20vbk8ybS8zYU9iVHlHRHBpVW5hRFBiR3gKRWkxN0pLeHZxaEwrR1RsUXFBWHB2RnF1M3VnYm8rVElFaDJGTTA3WEZIZTRLdDYzWS9zdkZMekFVVUlpWlgycQo2MU9rZG9yZFVvR1lVY25ia3VOaU02RDZKUU94dXMzL3YrT3FrZ0M3VE41aFpUR2RjSkVxSlBBSGJVY05GSWQrCnVZNVFSRjdOTzNBajFRVzh1WkZ6VTM2ZFRVOFhYbmFXVEVhRFZUUm50NG92TXRSU0tnbGhEMkxGTnNidXAvRlMKM3J5eXRvRWpHR042V05IZGhMRjlaTjlLUmtEK0VmR2lUUjZiNkxDU0dNRWR0YjhabHAzUUdMZ1lmMGN5SWJ0Uwo1UllyZW9iMU1UMlpsVm91TW9haEhrZ1FzVzRuWTFpaWMyRWlKcUpMVm5EandoeW0zVGdqcGZkVlc0Q0R2c1phCkRoVnlUeFFwTXA5WGZUdFdqKzV3TktyWkh2THVJbzlmRWZLS04rQkFzalp6TEM5TmhHcmtINEplclBjU2psekMKaTFLL2FsZVB6RmZBYmMvRk9QQVZzUlFMVmxYZmExQTJPMVVDUzN0bkhXVDQ2WmI0KzVXZWROWExvemppTm10OAo3b25MY0YrczZQU3N3ZnhwblRuZU1GbGh4VDRIN09ndmFsQ25panFyTmpvbG9HSmRzZ0dqUkdjWUpvZzE2cnVYCmJXV1BwNU14K25ESlNBSnNGN0ZPaXp4QTkxNUY5VXJEV25SN01xUG5mNk1kVm1KcDBFMnpMdmw2QnJQdis5RmcKWllJU0IvV0xWME90ZXY3dE0xT3N5WW00SDZORDAvNkZWNHNLOHkxMzI3ekJRaEZyblp0c0pPaENEZUJ2em5WcAo1a2lqbEJFemxFVTM2ZEhac1Zycmx3eHg0bk5RNXNkRTA4Q1ZCbk94SUJzODIrcGgrZnhETU9sbnZCNmVOYTU4CmVMVU1xNzhudnJQMU1lcEdCNTMvS0RkQlAyRTk4YWNObWpwZEhPbTg2OFdFMnlwMEtPQmVhdkhkV2phd2VzNEUKd2xpdDdCZVF2ZGRaQlBDdmR1Mm4rQTc0QW5nUW55MllsUytQUVRvb2JKZGlQZ0JCcjRXUGZJVTFZaklnMmJxcwpZQm1vL1BzOHAxa0pvRDBLSWhTRFhoSXRsQ2loSTlwaDJkM0ZOOHdnc1ZZY0hTNDhtRDY5OXhJalF6dE9yenZJCnl2K0Z1WGI3bStEck0xNnpWdVNqQXNlRi9UbWlydzhEdkRyR2psQ3hHK3lTNUdJK3dZUVBwdXZJVXFpMzRkSHkKMVZoeWlraXRsTjNMVURtVW5mS3BOWFNlVjFvYW9xY0ZDNlhxMzZqeGFTM0gwWHN5WVh5OEw4VmVaK0h0UDRmUwpzdVBDeHhKZTIvd0NVMVhRK2F3VXZ5MFEzRVkvYWtpeDg2VTZBeWltMlJEUHB0NVhoRStoVkpiY3R1c1JhVjV2CmNCNzQ4N2NlRzk3ZVFLQVBJZ3lXRWlEYVhmSlJlVmlnOHJNSjF0TEtJQlhGMkc3T1VIbkUydkFQZi9zS2NseGgKbTRKdW1YVHhHNW1neS9kSWkveS9hVkgwMndyMXozTmxFL0czKytybzR6ekdVaUtKUGJ6amlmWHlEUUlzWjBwaQpKYTQ5UTh3SmhCblRrVE40RGVEb1BVc2RrdncyYTIrK1ZvZ3NmdTBvNjZCT3dZZm4vOE1wZnRjQjZ0Q05KclNkClVvRmFVaTBDZ2dJQkFPNXRKYkZ2RGl2d3YvbVN1WWdFZzZueVVwd3JySmlENWdpRHVsRVUzV3ZwM2lRdzc5ekwKdjdjdDd4MGFyemVPNVNsbVBkTFhCaWZQMDFqVFpZY01odmhydk83VnVveWExK3pueXNMQkxRNmQ0ZW82OEZQRApuWFJrc0pqQ0RrMnlHZkYvNHNZb09oUlprTHBSdUJSZWFwTU1HWEx0YTRWVWJRWVI0RWtHbVdEV2wrRGJIOE5yCjQ5enNPMldEa05NRDNlYzdkeTh6eC9PZ1ptdEtpbHNBc0dZcjBEaUdsL0VYZ0tVQ2l1SE83RU9zQ01JQWk4NzcKVmZhZzdnY2lHWTg0dTBXOEF1YzdqM2Nkd0VRelNEbHF5NzY0a1VTS01wWTh4Q1R2NTJZN3lpZXYzZWdCQjJUVAp4WUJ4dVNVR0ZIM3NTY0plMVJYZjRWL2RuWFVhQWo2TFFxY3Byem5KcXZTWnBmcHAzNW1jMUhBc0NNeUxlc25uCnVEN0hoNzQ4TUkyelpodC80ekJsbUs4L1VGenEvUjZua1BNMm53Kzg1RUwwR3dJdjJmTzFlcUloUGtqQ1lUZjEKRXA5OGZnY2N4bVVUVTBQQVdXV0R1RFN1ZHQ0cVRXb1dYeWRISXhLWnFMRUYvRGZlbWRmcVVJRFRvY1Yvb1NDdAppMlJRaTgzVlJWNFkreGo3ZnllLzVzRlRYVXQ5NUtOekxXSmtxK0NUd1ZyZFU5MjBmbkQxcURIT3hTb1BETXA5CjVuYzVkbFFrWWMwNmJkRjRxSkZxcFc3dUZDVmc2WjJqM0pTamtCK0J3VVp6TFNUMVlLU0R5VVBZc24vSSszL2sKenBJMFR6LysrWTZEN3htdUZWOVp3RzJtUHpwekNyT3llb1IvOU5DVWhhSTlQK3BZNjVaazNYdGZBb0lDQVFEagp0TDBBeEdFSFdnZURHdnZvbnd0b3FuYUV6UGFnRzVSRGtIaCtTbVB2RWlVUFhtV0lQTU5QaUJLaDRmcHBXcWZRCjF5b2U0M0dLMjhmR3JQMGgyU2MzL2hvVHkwRzlDcFo5NkVoMHhnd0k5OU9OcnprcGQ2bE1pVDF5R0I0WnpSMWYKaGpCVndFalM4My9Qb0RnaUpBNzc4WkttbnN0UHpka2lzbkNiRU1xNDFKNVRCWDN0eHJsZ1JmamJJcWw3MitwMgorOExwUmtuSnQydnRHRW4zazhha3RlR3EycEdZcTlRTzI5UndjaTdib0kzdllHQlM4eThmSWxKOThqK0I2a1FaClJXcmNwQ2hqSmhyMW95SFBrcTBxOXNVb29tNFZmM2UrMkxCTDdidXVhMURGQTgxN2FkUzJtd1hTOGlQbzA2YlcKdlk2ZVhvQ2RYVmFMbng4TWxBYVdlaFNlWVVCMkJMR0p4N1dQZXlUT09PdS9NQm5uM1ZYemYySVNiTkg5NXV0MgpVb2lmYm9FT0VPUVc5eXNrQWNSeHM2UVFyYnVqUSs2bkl5UmdKNUJraWxNT1k2TGJMK1F3d25oSEVCZ1RUdThICml6T04xQVUvdEtpbUpyMnM3RVovdUNONER3MERiYmRFamMzOWo0bTAzV2RscWZLL3RNSUw3dHYxVjRVWHpScEIKNUJTUTFvRm85eFNUNTI5aFhTNUtFQi9IL291NmR0OG1hbUpTQ0xvN05ybkVTcWlHWHZQRG9Ybm53NFFrL1JUNAo1YTNsMTVYTFZVVjlwUmI3c1B2QlBBbnRodU5IR3VHMFY5Znk4OHY3anJLZmMrZDFaTkF2QlRKSTRhVmtKTHBFClErVkEyVHQxdTB4ajhmTFYrYlZEaXZ3VnhpMDZOYXRxdjllSUJzTWxvd0tDQWdBdUhMZjBpQmtDa0k1Z2Myc2sKamxMMGxHUTd4Z3FjZUs0TnFZUm9XQk8yNGtWUFZKT2ZiVnlIemY5MzdvaEN3NFU0cTRoN2RaREFOR2FZd0ZIYgplNlhDOS90VGFjeXBrdXo5NlpxQ2JpQUx1cWROeU5aZ0xPNFA2OFZuMWVnMFNLVFIyeno5dkJ2M2daY0hJZlRyCkk1T1RHdnoxQ0V3S1BsalRtck41RENpdjNQRUUwUHhrckVJbW9SMmZ0WUZWL21KMWJUL1F4ai8rczEvN2tqQU8KQjZVV0xaVVl5WmNyVHJOWHRwVXJ0UHhtM2lmWGRZbVVuM0Z4d0pBb213UzhlV2xteEVUL2VicDJmQytLUVN6UAp4Z0xmd1F4L2FBYituWVFGN013aExxRWJhZDBPR056WU9FanpYWXRFU05lL3Z1cEpDRlJINWNQTjZhdWhVVVZyCjJUMHIzVmtCWVNxS0lnbEMxQ1VsclhvOHM1ZUVEOW5Rb05zMmNScWt4VGxTdm9hWi9QTHdra1drWnlkZ3dTWHgKUHRFKzZLcDh2YmliNW1BdTNSaFhGUnRCcmhKQXVpOVpSakd5M0wzM0hDNldyOVVqdmxqTDFGelUrNFVMMUx5aQpMdTk2Ump6WFJSYW1IaFU0clBtdUU2ZzhNaklRWTIzRFJ5MDFXb3FmWlljRCt1cmRXdzZ0bm1TL3NTTFREZWNoCllZNCtnRi9wa0VvT0M4NURpN3dFbHM1UHk4REFNS2IxcHNIaS94OE9pUGJOWFdhTjQ3c2VYTFRnTG5XQkFTeE4KaTdxR21OZXY4RVYwSGFSMmlHcUhodUZ2R01MMUNlYnlSa3RaWlhxS1V3THErRU5QQVNjckNNMjVwelNGVm1pVQpkb2xSaFBuUk9WaGJGMk44TEhScjR0Z2ZHd0tDQWdFQXVad0JHRmY3TTQvcVlhOGtPaGt5cG8yVThHbFdlMm9mCnIvZGFrSzg0eUk2RTBRTkVSZ29wdG5HWHBvZGFwSGcySk9ET3Y4RHNNNkUxTmppYVdmWDFwd21rM2crbnRWMmwKRUZyQWZSZFdoaFRsU0MvVnEzeVQ3d1JMcHU0TDAwSkVPREpjd2Zsc0l6QkROYzVIRTJWTEpZbGozaGZBYUh2RwpEQ2RoN0xTQ1dxbE5xU1RuNG1ORGhqdGpQOVVBVENzVjh3a0RkejFKTm5raUszREtFbHBONk1NdGdTU0syK1RzCmhYUWh0Y3NOY1E5dHd2dFBhUzQ3Y2VoN1Q1aWd0ZGhzekNDdW04M2Y4Zm9FcmNmYzdxT0VMbXBhaWVYbFQvYkkKZURPUGVVVCs0STB2bUhpaURZQlYyTWVDdHRHVC9keFF1ZWhvRWFXOHR3bDNXM1pJUyt0NWR6MXFBelFJNUdxdApBVDllT3VmSk42UmtYa0xxU3ZzN2JiR2ZFcC9MaUdpcjlKWVFNYzFVdTA5L2JVenF5SDM4VUNaN2pQRGc2NU9iClBIaEQxWEZLblBtMy9CbXhqWE43VVZlanpXRk1EcWtmNUlsT2E4U3d4cDRQZnVoRFltcHlpUGRqU2lFU25ZSFkKaXJRQWZqaDdxb2R6R2dhdkRoOWNzWGR4cW9vOXZnbjg1a3J4aktLZGVCODNrZHhzQ1BSNG4veUd1M0k5R2JCOQo4NFZ5UWFaRmo3RHJPaHNWUmZxdVB3QW9LNGhPOWd1cUJiekt4SGkzN0xmRVhrZXM5VnJ0ekRTUmJ5R3RyNjgwCjNkbGcrUFJMaVBGbm50eE9objIzeVN3Mk1meGs0YjJpYTdUZ2NiemhYL1Zkcm5aeFdJUWtnanNQZ3Z3NHI2TkIKNkZFYWNoSDVEbnNDZ2dJQkFPcjdZaktLMVZTUk1KdUp6Rm9hWHFweTUzeU5tc3ZFck9sSWZQKzB3OWpJQkZNbwpXdHZtNWNmTVA4TXpVVmJ0RVhwaUFiQklnelpsWVhGNmVLeGZWeXlKVE5MOWViaDRyaDNYZUlueEwrcG0xN3p5Ck5LOGlQZHdpbFQzaHBELzA3aWcyNER4Njd4MkFYVDBqZEEvU3hKbC94SFc3U1A4L0lwTkxvczFMS2VFMHNWNjkKR2M2UVdac2dZdzk4aG5KczVJdHIyK3QrUG1oV29lUHVwUmZMUW1qYVd4VlVmeFZBdC9ZcDQvNldQZDA5ZnZwRQpmOUVESi9tT1ZPaWdJY1FmOTl3cFpwVFZpdVVzWm1YdU9BZWFCeUY5c3ozSTYxcTBUVy8rUzBYb3c3aXlJQWdnCnZ2SXJJUlF0dzNOVDJYbW1wc041b0xNOWhpNTFZVXpOYkV6L0VPMkxnMmhnOEhiOUhxcFppT3cxNVIxOTM0eUgKeThZY1YzMFQ4MWh4aDJxUEQwRmwzTUJReHZobVBMWGFPTHI4VlB4dlZITGh2N1g5Sy9wSXhRTkVPUTJxVzZYRwpPTUJJekRZNDlLV3lvMVl5S096dkFFUDIyL3FVT25qNXJualFBM1ArQ0FTT0ZBTE9mRlNIQ2pzM2xZL0JOQUdTCmtGbmtnOTk2a01GRDJ6a1Y4cXRYb3dzdHE2UExZUnNJb05zOWd0TDZwdkFYaXI2MUZhNnZrYy8rS0ttdXptNDIKUXRtVGtvYUtsdlNidnRnL0NpTlZpQUhBVlAzZ2dyUEZXTFJIaStpN1dNRHhiZFR3TzE1UiszS2h2c3BYZG5JQgpZTWthSG44RUJtWUFaNVVrRUNKT1Vtb0l2S1p6RjB0UlNMTk9KRU8vekQ4MUtKYU9sdU83RmZnWGN6c2IKLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K"

redis:
  enabled: true # 是否启用Redis部署
  auth:
    enabled: true
    password: "sigma"
  master:
    service:
      type: NodePort
      nodePorts:
        redis: 30060
  replica:
    replicaCount: 1

minio:
  enabled: true # 是否启用MinIO部署
  accessKey: "sigma"
  secretKey: "sigma-sigma"
  service:
    type: NodePort
    nodePort: 32000
  buckets:
    - name: sigma
      policy: none
      purge: false

mysql:
  enabled: true # 是否启用MySQL部署
  auth:
    rootPassword: "sigma"
    createDatabase: true
    database: "sigma"
    username: "sigma"
    password: "sigma"
  primary:
    service:
      type: NodePort
      nodePorts:
        mysql: 30306
