apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sigma.worker" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "sigma.worker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.autoscaling.replicaCount.worker }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sigma.worker.labels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sigma.worker.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "sigma.fullname" . | quote }}
      containers:
        - name: {{ include "sigma.worker" . | quote }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - sigma
          args:
            - worker
            - --config=/etc/sigma/config.yaml
          ports:
            - name: http
              containerPort: {{ .Values.service.worker.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.worker.port }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.worker.port }}
          volumeMounts:
            - name: config
              mountPath: /etc/sigma/config.yaml
              subPath: config.yaml
              readOnly: true
            {{- if semverCompare ">= 1.31" .Capabilities.KubeVersion.Version }}
            - name: trivy
              mountPath: /opt/trivy
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ printf "%s-config" ( include "sigma.fullname" . ) | quote }}
        {{- if semverCompare ">= 1.31" .Capabilities.KubeVersion.Version }}
        - name: trivy
          image:
            reference: "{{ .Values.image.registry }}/{{ .Values.image.trivy.repository }}:{{ .Values.image.trivy.tag }}"
            pullPolicy: {{ .Values.image.pullPolicy | quote }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
