apiVersion: v1
kind: Service
metadata:
  name: {{ include "sigma.worker" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "sigma.worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  ports:
    - port: {{ .Values.service.worker.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sigma.worker.labels" . | nindent 4 }}
