linters:
  enable:
    - cyclop
    - exportloopref
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - prealloc
    - unconvert
    - unparam
    - goimports
    - whitespace
    - gci

linters-settings:
  whitespace:
    multi-func: true
  cyclop:
    max-complexity: 50
    package-average: 30
    skip-tests: true
  gci:
    sections:
      - standard
      - blank
      - default
      - prefix(github.com/go-sigma/sigma)
      - dot
