run:
  go: "1.23"

linters:
  enable:
    - cyclop
    - copyloopvar
    - gocritic
    - gosec
    - ineffassign
    - misspell
    - prealloc
    - unconvert
    - unparam
    - goimports
    - whitespace
    - gci
    - misspell
    - bidichk
    - unparam
    - unused
    - varnamelen
    - whitespace
    - asciicheck

linters-settings:
  whitespace:
    multi-func: true
  cyclop:
    max-complexity: 50
    package-average: 50
    skip-tests: true
  gci:
    sections:
      - standard
      - blank
      - default
      - prefix(github.com/go-sigma/sigma)
      - dot
  varnamelen:
    max-distance: 6
    min-name-length: 1
