version: "2"
run:
  go: "1.27"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - gocritic
    - gosec
    - misspell
    - prealloc
    - unconvert
    - unparam
    - varnamelen
    - whitespace
  settings:
    cyclop:
      max-complexity: 50
      package-average: 50
    varnamelen:
      max-distance: 6
      min-name-length: 1
    whitespace:
      multi-func: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - goimports
  settings:
    gci:
      sections:
        - standard
        - blank
        - default
        - prefix(github.com/go-sigma/sigma)
        - dot
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
