version: '2'
services:
  ximager:
    image: ximager:latest
    ports:
      - "5001:5000"
      - "3001:3000"
    volumes:
      - ./images:/images
    environment:
      XIMAGER_IMAGE_DIR: /images
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ximager
      MYSQL_DATABASE: ximager
      MYSQL_USER: ximager
      MYSQL_PASSWORD: ximager
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass ximager
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "ximager", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
  minio:
    image: minio/minio:RELEASE.2021-07-05T00-50-56Z
    ports:
      - "9000:9000"
      - "9001:9001"
    entrypoint: sh
    environment:
      MINIO_ACCESS_KEY: ximager
      MINIO_SECRET_KEY: ximager-ximager
    command: mkdir -p /data/ximager && minio server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ximager
      POSTGRES_USER: ximager
      POSTGRES_DB: ximager
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ximager"]
      interval: 10s
      timeout: 5s
      retries: 10
