version: "2"
services:
  sigma:
    container_name: sigma
    image: ghcr.io/go-sigma/sigma:latest
    ports:
      - "3000:3000"
    command: ["sigma", "server"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD:-/app}/conf/config-compose.yaml:/etc/sigma/config.yaml
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - default
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sigma
      MYSQL_DATABASE: sigma
      MYSQL_USER: sigma
      MYSQL_PASSWORD: sigma
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "sigma",
          "--password=sigma",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - default
  redis:
    container_name: redis
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass sigma
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "sigma", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - default
  minio:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2023-08-04T17-40-21Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: sigma
      MINIO_ROOT_PASSWORD: sigma-sigma
      MINIO_REGION_NAME: cn-north-1
    entrypoint: ""
    command: /bin/sh -c 'mkdir -p /data/sigma && minio server /data --console-address ":9001"'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - default
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sigma
      POSTGRES_USER: sigma
      POSTGRES_DB: sigma
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sigma"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - default
  pma:
    container_name: pma
    image: linuxserver/phpmyadmin:5.2.1
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: sigma
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - default
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.8
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: sigma@tosone.cn
      PGADMIN_DEFAULT_PASSWORD: sigma
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "80"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - default
networks:
  default:
    name: ${DOCKER_NETWORK:-sigma}
