version: '2'
services:
  ximager:
    image: sigma:latest
    ports:
      - "3000:3000"
    command: server
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ximager
      MYSQL_DATABASE: ximager
      MYSQL_USER: ximager
      MYSQL_PASSWORD: ximager
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass sigma
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "sigma", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
  minio:
    image: quay.io/minio/minio:RELEASE.2023-07-07T07-13-57Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ximager
      MINIO_ROOT_PASSWORD: ximager-ximager
      MINIO_REGION_NAME: cn-north-1
    entrypoint: ''
    command: /bin/sh -c 'mkdir -p /data/ximager && minio server /data --console-address ":9001"'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 10
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ximager
      POSTGRES_USER: ximager
      POSTGRES_DB: ximager
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ximager"]
      interval: 10s
      timeout: 5s
      retries: 10
  pma:
    image: phpmyadmin/phpmyadmin:5.2.1
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ximager
      PMA_PASSWORD: ximager
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 10
  pgadmin:
    image: dpage/pgadmin4:7.4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ximager@tosone.cn
      PGADMIN_DEFAULT_PASSWORD: ximager
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "80"]
      interval: 10s
      timeout: 5s
      retries: 10
