apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: sigma
build:
  tagPolicy:
    dateTime:
      format: "20060102150405"
      timezone: "Local"
  artifacts:
    - image: go-sigma/sigma
      hooks:
        before:
          - command:
              - make
              - build-linux
      context: .
      docker:
        dockerfile: ./build/local.Dockerfile
      platforms:
        - linux/amd64
deploy:
  helm:
    releases:
      - name: sigma
        createNamespace: true
        namespace: sigma
        chartPath: deploy/sigma
        skipBuildDependencies: true
