// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-sigma/sigma/pkg/service/analytics (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=analytics_mocks.go -package=analytics github.com/go-sigma/sigma/pkg/service/analytics Service
//

// Package analytics is a generated GoMock package.
package analytics

import (
	context "context"
	reflect "reflect"

	api "github.com/go-sigma/sigma/pkg/api"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Flush mocks base method.
func (m *MockService) Flush(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockServiceMockRecorder) Flush(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockService)(nil).Flush), ctx)
}

// GetNamespaceTrends mocks base method.
func (m *MockService) GetNamespaceTrends(ctx context.Context, namespaceID string, days int) ([]api.NamespaceHourlyMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNamespaceTrends", ctx, namespaceID, days)
	ret0, _ := ret[0].([]api.NamespaceHourlyMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNamespaceTrends indicates an expected call of GetNamespaceTrends.
func (mr *MockServiceMockRecorder) GetNamespaceTrends(ctx, namespaceID, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespaceTrends", reflect.TypeOf((*MockService)(nil).GetNamespaceTrends), ctx, namespaceID, days)
}

// GetUserPushHeatmap mocks base method.
func (m *MockService) GetUserPushHeatmap(ctx context.Context, userID string, days int) ([]api.DailyCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPushHeatmap", ctx, userID, days)
	ret0, _ := ret[0].([]api.DailyCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPushHeatmap indicates an expected call of GetUserPushHeatmap.
func (mr *MockServiceMockRecorder) GetUserPushHeatmap(ctx, userID, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPushHeatmap", reflect.TypeOf((*MockService)(nil).GetUserPushHeatmap), ctx, userID, days)
}

// RecordNamespaceSizeDelta mocks base method.
func (m *MockService) RecordNamespaceSizeDelta(ctx context.Context, namespaceID string, delta int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordNamespaceSizeDelta", ctx, namespaceID, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordNamespaceSizeDelta indicates an expected call of RecordNamespaceSizeDelta.
func (mr *MockServiceMockRecorder) RecordNamespaceSizeDelta(ctx, namespaceID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordNamespaceSizeDelta", reflect.TypeOf((*MockService)(nil).RecordNamespaceSizeDelta), ctx, namespaceID, delta)
}

// RecordNamespaceTagDelta mocks base method.
func (m *MockService) RecordNamespaceTagDelta(ctx context.Context, namespaceID string, delta int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordNamespaceTagDelta", ctx, namespaceID, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordNamespaceTagDelta indicates an expected call of RecordNamespaceTagDelta.
func (mr *MockServiceMockRecorder) RecordNamespaceTagDelta(ctx, namespaceID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordNamespaceTagDelta", reflect.TypeOf((*MockService)(nil).RecordNamespaceTagDelta), ctx, namespaceID, delta)
}

// RecordPull mocks base method.
func (m *MockService) RecordPull(ctx context.Context, event PullEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordPull", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordPull indicates an expected call of RecordPull.
func (mr *MockServiceMockRecorder) RecordPull(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPull", reflect.TypeOf((*MockService)(nil).RecordPull), ctx, event)
}

// RecordPush mocks base method.
func (m *MockService) RecordPush(ctx context.Context, event PushEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordPush", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordPush indicates an expected call of RecordPush.
func (mr *MockServiceMockRecorder) RecordPush(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPush", reflect.TypeOf((*MockService)(nil).RecordPush), ctx, event)
}
