// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-sigma/sigma/pkg/dal/dao (interfaces: NamespaceMemberServiceFactory)
//
// Generated by this command:
//
//	mockgen -destination=mocks/namespace_member_factory.go -package=mocks github.com/go-sigma/sigma/pkg/dal/dao NamespaceMemberServiceFactory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dao "github.com/go-sigma/sigma/pkg/dal/dao"
	query "github.com/go-sigma/sigma/pkg/dal/query"
	gomock "go.uber.org/mock/gomock"
)

// MockNamespaceMemberServiceFactory is a mock of NamespaceMemberServiceFactory interface.
type MockNamespaceMemberServiceFactory struct {
	ctrl     *gomock.Controller
	recorder *MockNamespaceMemberServiceFactoryMockRecorder
	isgomock struct{}
}

// MockNamespaceMemberServiceFactoryMockRecorder is the mock recorder for MockNamespaceMemberServiceFactory.
type MockNamespaceMemberServiceFactoryMockRecorder struct {
	mock *MockNamespaceMemberServiceFactory
}

// NewMockNamespaceMemberServiceFactory creates a new mock instance.
func NewMockNamespaceMemberServiceFactory(ctrl *gomock.Controller) *MockNamespaceMemberServiceFactory {
	mock := &MockNamespaceMemberServiceFactory{ctrl: ctrl}
	mock.recorder = &MockNamespaceMemberServiceFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamespaceMemberServiceFactory) EXPECT() *MockNamespaceMemberServiceFactoryMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockNamespaceMemberServiceFactory) New(txs ...*query.Query) dao.NamespaceMemberService {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range txs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "New", varargs...)
	ret0, _ := ret[0].(dao.NamespaceMemberService)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockNamespaceMemberServiceFactoryMockRecorder) New(txs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockNamespaceMemberServiceFactory)(nil).New), txs...)
}
