// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ximager/ximager/pkg/dal/dao (interfaces: ProxyTaskServiceFactory)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dao "github.com/ximager/ximager/pkg/dal/dao"
	query "github.com/ximager/ximager/pkg/dal/query"
)

// MockProxyTaskServiceFactory is a mock of ProxyTaskServiceFactory interface.
type MockProxyTaskServiceFactory struct {
	ctrl     *gomock.Controller
	recorder *MockProxyTaskServiceFactoryMockRecorder
}

// MockProxyTaskServiceFactoryMockRecorder is the mock recorder for MockProxyTaskServiceFactory.
type MockProxyTaskServiceFactoryMockRecorder struct {
	mock *MockProxyTaskServiceFactory
}

// NewMockProxyTaskServiceFactory creates a new mock instance.
func NewMockProxyTaskServiceFactory(ctrl *gomock.Controller) *MockProxyTaskServiceFactory {
	mock := &MockProxyTaskServiceFactory{ctrl: ctrl}
	mock.recorder = &MockProxyTaskServiceFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProxyTaskServiceFactory) EXPECT() *MockProxyTaskServiceFactoryMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockProxyTaskServiceFactory) New(arg0 ...*query.Query) dao.ProxyTaskService {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "New", varargs...)
	ret0, _ := ret[0].(dao.ProxyTaskService)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockProxyTaskServiceFactoryMockRecorder) New(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockProxyTaskServiceFactory)(nil).New), arg0...)
}
