// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-sigma/sigma/pkg/dal/dao (interfaces: SettingService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/setting.go -package=mocks github.com/go-sigma/sigma/pkg/dal/dao SettingService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/go-sigma/sigma/pkg/dal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSettingService is a mock of SettingService interface.
type MockSettingService struct {
	ctrl     *gomock.Controller
	recorder *MockSettingServiceMockRecorder
	isgomock struct{}
}

// MockSettingServiceMockRecorder is the mock recorder for MockSettingService.
type MockSettingServiceMockRecorder struct {
	mock *MockSettingService
}

// NewMockSettingService creates a new mock instance.
func NewMockSettingService(ctrl *gomock.Controller) *MockSettingService {
	mock := &MockSettingService{ctrl: ctrl}
	mock.recorder = &MockSettingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingService) EXPECT() *MockSettingServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSettingService) Create(ctx context.Context, key string, val []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSettingServiceMockRecorder) Create(ctx, key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSettingService)(nil).Create), ctx, key, val)
}

// Delete mocks base method.
func (m *MockSettingService) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSettingServiceMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSettingService)(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockSettingService) Get(ctx context.Context, key string) (*models.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(*models.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSettingServiceMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSettingService)(nil).Get), ctx, key)
}

// Update mocks base method.
func (m *MockSettingService) Update(ctx context.Context, key string, val []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSettingServiceMockRecorder) Update(ctx, key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSettingService)(nil).Update), ctx, key, val)
}
