// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/go-sigma/sigma/pkg/dal/models"
)

func newDaemonGcBlobRule(db *gorm.DB, opts ...gen.DOOption) daemonGcBlobRule {
	_daemonGcBlobRule := daemonGcBlobRule{}

	_daemonGcBlobRule.daemonGcBlobRuleDo.UseDB(db, opts...)
	_daemonGcBlobRule.daemonGcBlobRuleDo.UseModel(&models.DaemonGcBlobRule{})

	tableName := _daemonGcBlobRule.daemonGcBlobRuleDo.TableName()
	_daemonGcBlobRule.ALL = field.NewAsterisk(tableName)
	_daemonGcBlobRule.CreatedAt = field.NewTime(tableName, "created_at")
	_daemonGcBlobRule.UpdatedAt = field.NewTime(tableName, "updated_at")
	_daemonGcBlobRule.DeletedAt = field.NewUint(tableName, "deleted_at")
	_daemonGcBlobRule.ID = field.NewInt64(tableName, "id")
	_daemonGcBlobRule.IsRunning = field.NewBool(tableName, "is_running")
	_daemonGcBlobRule.RetentionDay = field.NewInt(tableName, "retention_day")
	_daemonGcBlobRule.CronEnabled = field.NewBool(tableName, "cron_enabled")
	_daemonGcBlobRule.CronRule = field.NewString(tableName, "cron_rule")
	_daemonGcBlobRule.CronNextTrigger = field.NewTime(tableName, "cron_next_trigger")

	_daemonGcBlobRule.fillFieldMap()

	return _daemonGcBlobRule
}

type daemonGcBlobRule struct {
	daemonGcBlobRuleDo daemonGcBlobRuleDo

	ALL             field.Asterisk
	CreatedAt       field.Time
	UpdatedAt       field.Time
	DeletedAt       field.Uint
	ID              field.Int64
	IsRunning       field.Bool
	RetentionDay    field.Int
	CronEnabled     field.Bool
	CronRule        field.String
	CronNextTrigger field.Time

	fieldMap map[string]field.Expr
}

func (d daemonGcBlobRule) Table(newTableName string) *daemonGcBlobRule {
	d.daemonGcBlobRuleDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d daemonGcBlobRule) As(alias string) *daemonGcBlobRule {
	d.daemonGcBlobRuleDo.DO = *(d.daemonGcBlobRuleDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *daemonGcBlobRule) updateTableName(table string) *daemonGcBlobRule {
	d.ALL = field.NewAsterisk(table)
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.DeletedAt = field.NewUint(table, "deleted_at")
	d.ID = field.NewInt64(table, "id")
	d.IsRunning = field.NewBool(table, "is_running")
	d.RetentionDay = field.NewInt(table, "retention_day")
	d.CronEnabled = field.NewBool(table, "cron_enabled")
	d.CronRule = field.NewString(table, "cron_rule")
	d.CronNextTrigger = field.NewTime(table, "cron_next_trigger")

	d.fillFieldMap()

	return d
}

func (d *daemonGcBlobRule) WithContext(ctx context.Context) *daemonGcBlobRuleDo {
	return d.daemonGcBlobRuleDo.WithContext(ctx)
}

func (d daemonGcBlobRule) TableName() string { return d.daemonGcBlobRuleDo.TableName() }

func (d daemonGcBlobRule) Alias() string { return d.daemonGcBlobRuleDo.Alias() }

func (d daemonGcBlobRule) Columns(cols ...field.Expr) gen.Columns {
	return d.daemonGcBlobRuleDo.Columns(cols...)
}

func (d *daemonGcBlobRule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *daemonGcBlobRule) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 9)
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["deleted_at"] = d.DeletedAt
	d.fieldMap["id"] = d.ID
	d.fieldMap["is_running"] = d.IsRunning
	d.fieldMap["retention_day"] = d.RetentionDay
	d.fieldMap["cron_enabled"] = d.CronEnabled
	d.fieldMap["cron_rule"] = d.CronRule
	d.fieldMap["cron_next_trigger"] = d.CronNextTrigger
}

func (d daemonGcBlobRule) clone(db *gorm.DB) daemonGcBlobRule {
	d.daemonGcBlobRuleDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d daemonGcBlobRule) replaceDB(db *gorm.DB) daemonGcBlobRule {
	d.daemonGcBlobRuleDo.ReplaceDB(db)
	return d
}

type daemonGcBlobRuleDo struct{ gen.DO }

func (d daemonGcBlobRuleDo) Debug() *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Debug())
}

func (d daemonGcBlobRuleDo) WithContext(ctx context.Context) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d daemonGcBlobRuleDo) ReadDB() *daemonGcBlobRuleDo {
	return d.Clauses(dbresolver.Read)
}

func (d daemonGcBlobRuleDo) WriteDB() *daemonGcBlobRuleDo {
	return d.Clauses(dbresolver.Write)
}

func (d daemonGcBlobRuleDo) Session(config *gorm.Session) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Session(config))
}

func (d daemonGcBlobRuleDo) Clauses(conds ...clause.Expression) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d daemonGcBlobRuleDo) Returning(value interface{}, columns ...string) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d daemonGcBlobRuleDo) Not(conds ...gen.Condition) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d daemonGcBlobRuleDo) Or(conds ...gen.Condition) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d daemonGcBlobRuleDo) Select(conds ...field.Expr) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d daemonGcBlobRuleDo) Where(conds ...gen.Condition) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d daemonGcBlobRuleDo) Order(conds ...field.Expr) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d daemonGcBlobRuleDo) Distinct(cols ...field.Expr) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d daemonGcBlobRuleDo) Omit(cols ...field.Expr) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d daemonGcBlobRuleDo) Join(table schema.Tabler, on ...field.Expr) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d daemonGcBlobRuleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d daemonGcBlobRuleDo) RightJoin(table schema.Tabler, on ...field.Expr) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d daemonGcBlobRuleDo) Group(cols ...field.Expr) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d daemonGcBlobRuleDo) Having(conds ...gen.Condition) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d daemonGcBlobRuleDo) Limit(limit int) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d daemonGcBlobRuleDo) Offset(offset int) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d daemonGcBlobRuleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d daemonGcBlobRuleDo) Unscoped() *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Unscoped())
}

func (d daemonGcBlobRuleDo) Create(values ...*models.DaemonGcBlobRule) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d daemonGcBlobRuleDo) CreateInBatches(values []*models.DaemonGcBlobRule, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d daemonGcBlobRuleDo) Save(values ...*models.DaemonGcBlobRule) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d daemonGcBlobRuleDo) First() (*models.DaemonGcBlobRule, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.DaemonGcBlobRule), nil
	}
}

func (d daemonGcBlobRuleDo) Take() (*models.DaemonGcBlobRule, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.DaemonGcBlobRule), nil
	}
}

func (d daemonGcBlobRuleDo) Last() (*models.DaemonGcBlobRule, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.DaemonGcBlobRule), nil
	}
}

func (d daemonGcBlobRuleDo) Find() ([]*models.DaemonGcBlobRule, error) {
	result, err := d.DO.Find()
	return result.([]*models.DaemonGcBlobRule), err
}

func (d daemonGcBlobRuleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.DaemonGcBlobRule, err error) {
	buf := make([]*models.DaemonGcBlobRule, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d daemonGcBlobRuleDo) FindInBatches(result *[]*models.DaemonGcBlobRule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d daemonGcBlobRuleDo) Attrs(attrs ...field.AssignExpr) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d daemonGcBlobRuleDo) Assign(attrs ...field.AssignExpr) *daemonGcBlobRuleDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d daemonGcBlobRuleDo) Joins(fields ...field.RelationField) *daemonGcBlobRuleDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d daemonGcBlobRuleDo) Preload(fields ...field.RelationField) *daemonGcBlobRuleDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d daemonGcBlobRuleDo) FirstOrInit() (*models.DaemonGcBlobRule, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.DaemonGcBlobRule), nil
	}
}

func (d daemonGcBlobRuleDo) FirstOrCreate() (*models.DaemonGcBlobRule, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.DaemonGcBlobRule), nil
	}
}

func (d daemonGcBlobRuleDo) FindByPage(offset int, limit int) (result []*models.DaemonGcBlobRule, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d daemonGcBlobRuleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d daemonGcBlobRuleDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d daemonGcBlobRuleDo) Delete(models ...*models.DaemonGcBlobRule) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *daemonGcBlobRuleDo) withDO(do gen.Dao) *daemonGcBlobRuleDo {
	d.DO = *do.(*gen.DO)
	return d
}
