// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                     = new(Query)
	Artifact              *artifact
	ArtifactSbom          *artifactSbom
	ArtifactVulnerability *artifactVulnerability
	Blob                  *blob
	BlobUpload            *blobUpload
	Namespace             *namespace
	ProxyArtifactBlob     *proxyArtifactBlob
	ProxyArtifactTask     *proxyArtifactTask
	ProxyTagTask          *proxyTagTask
	Repository            *repository
	Tag                   *tag
	User                  *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Artifact = &Q.Artifact
	ArtifactSbom = &Q.ArtifactSbom
	ArtifactVulnerability = &Q.ArtifactVulnerability
	Blob = &Q.Blob
	BlobUpload = &Q.BlobUpload
	Namespace = &Q.Namespace
	ProxyArtifactBlob = &Q.ProxyArtifactBlob
	ProxyArtifactTask = &Q.ProxyArtifactTask
	ProxyTagTask = &Q.ProxyTagTask
	Repository = &Q.Repository
	Tag = &Q.Tag
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                    db,
		Artifact:              newArtifact(db, opts...),
		ArtifactSbom:          newArtifactSbom(db, opts...),
		ArtifactVulnerability: newArtifactVulnerability(db, opts...),
		Blob:                  newBlob(db, opts...),
		BlobUpload:            newBlobUpload(db, opts...),
		Namespace:             newNamespace(db, opts...),
		ProxyArtifactBlob:     newProxyArtifactBlob(db, opts...),
		ProxyArtifactTask:     newProxyArtifactTask(db, opts...),
		ProxyTagTask:          newProxyTagTask(db, opts...),
		Repository:            newRepository(db, opts...),
		Tag:                   newTag(db, opts...),
		User:                  newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Artifact              artifact
	ArtifactSbom          artifactSbom
	ArtifactVulnerability artifactVulnerability
	Blob                  blob
	BlobUpload            blobUpload
	Namespace             namespace
	ProxyArtifactBlob     proxyArtifactBlob
	ProxyArtifactTask     proxyArtifactTask
	ProxyTagTask          proxyTagTask
	Repository            repository
	Tag                   tag
	User                  user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Artifact:              q.Artifact.clone(db),
		ArtifactSbom:          q.ArtifactSbom.clone(db),
		ArtifactVulnerability: q.ArtifactVulnerability.clone(db),
		Blob:                  q.Blob.clone(db),
		BlobUpload:            q.BlobUpload.clone(db),
		Namespace:             q.Namespace.clone(db),
		ProxyArtifactBlob:     q.ProxyArtifactBlob.clone(db),
		ProxyArtifactTask:     q.ProxyArtifactTask.clone(db),
		ProxyTagTask:          q.ProxyTagTask.clone(db),
		Repository:            q.Repository.clone(db),
		Tag:                   q.Tag.clone(db),
		User:                  q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Artifact:              q.Artifact.replaceDB(db),
		ArtifactSbom:          q.ArtifactSbom.replaceDB(db),
		ArtifactVulnerability: q.ArtifactVulnerability.replaceDB(db),
		Blob:                  q.Blob.replaceDB(db),
		BlobUpload:            q.BlobUpload.replaceDB(db),
		Namespace:             q.Namespace.replaceDB(db),
		ProxyArtifactBlob:     q.ProxyArtifactBlob.replaceDB(db),
		ProxyArtifactTask:     q.ProxyArtifactTask.replaceDB(db),
		ProxyTagTask:          q.ProxyTagTask.replaceDB(db),
		Repository:            q.Repository.replaceDB(db),
		Tag:                   q.Tag.replaceDB(db),
		User:                  q.User.replaceDB(db),
	}
}

type queryCtx struct {
	Artifact              *artifactDo
	ArtifactSbom          *artifactSbomDo
	ArtifactVulnerability *artifactVulnerabilityDo
	Blob                  *blobDo
	BlobUpload            *blobUploadDo
	Namespace             *namespaceDo
	ProxyArtifactBlob     *proxyArtifactBlobDo
	ProxyArtifactTask     *proxyArtifactTaskDo
	ProxyTagTask          *proxyTagTaskDo
	Repository            *repositoryDo
	Tag                   *tagDo
	User                  *userDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Artifact:              q.Artifact.WithContext(ctx),
		ArtifactSbom:          q.ArtifactSbom.WithContext(ctx),
		ArtifactVulnerability: q.ArtifactVulnerability.WithContext(ctx),
		Blob:                  q.Blob.WithContext(ctx),
		BlobUpload:            q.BlobUpload.WithContext(ctx),
		Namespace:             q.Namespace.WithContext(ctx),
		ProxyArtifactBlob:     q.ProxyArtifactBlob.WithContext(ctx),
		ProxyArtifactTask:     q.ProxyArtifactTask.WithContext(ctx),
		ProxyTagTask:          q.ProxyTagTask.WithContext(ctx),
		Repository:            q.Repository.WithContext(ctx),
		Tag:                   q.Tag.WithContext(ctx),
		User:                  q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
