// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                             = new(Query)
	Artifact                      *artifact
	ArtifactSbom                  *artifactSbom
	ArtifactVulnerability         *artifactVulnerability
	Audit                         *audit
	Blob                          *blob
	BlobUpload                    *blobUpload
	Builder                       *builder
	BuilderRunner                 *builderRunner
	CodeRepository                *codeRepository
	CodeRepositoryBranch          *codeRepositoryBranch
	CodeRepositoryCloneCredential *codeRepositoryCloneCredential
	CodeRepositoryOwner           *codeRepositoryOwner
	DaemonGcRecord                *daemonGcRecord
	DaemonGcRule                  *daemonGcRule
	DaemonGcRunner                *daemonGcRunner
	Namespace                     *namespace
	NamespaceActivityHourly       *namespaceActivityHourly
	NamespaceMember               *namespaceMember
	Repository                    *repository
	Setting                       *setting
	Tag                           *tag
	User                          *user
	User3rdParty                  *user3rdParty
	UserActivityHourly            *userActivityHourly
	UserRecoverCode               *userRecoverCode
	Webhook                       *webhook
	WebhookLog                    *webhookLog
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Artifact = &Q.Artifact
	ArtifactSbom = &Q.ArtifactSbom
	ArtifactVulnerability = &Q.ArtifactVulnerability
	Audit = &Q.Audit
	Blob = &Q.Blob
	BlobUpload = &Q.BlobUpload
	Builder = &Q.Builder
	BuilderRunner = &Q.BuilderRunner
	CodeRepository = &Q.CodeRepository
	CodeRepositoryBranch = &Q.CodeRepositoryBranch
	CodeRepositoryCloneCredential = &Q.CodeRepositoryCloneCredential
	CodeRepositoryOwner = &Q.CodeRepositoryOwner
	DaemonGcRecord = &Q.DaemonGcRecord
	DaemonGcRule = &Q.DaemonGcRule
	DaemonGcRunner = &Q.DaemonGcRunner
	Namespace = &Q.Namespace
	NamespaceActivityHourly = &Q.NamespaceActivityHourly
	NamespaceMember = &Q.NamespaceMember
	Repository = &Q.Repository
	Setting = &Q.Setting
	Tag = &Q.Tag
	User = &Q.User
	User3rdParty = &Q.User3rdParty
	UserActivityHourly = &Q.UserActivityHourly
	UserRecoverCode = &Q.UserRecoverCode
	Webhook = &Q.Webhook
	WebhookLog = &Q.WebhookLog
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                            db,
		Artifact:                      newArtifact(db, opts...),
		ArtifactSbom:                  newArtifactSbom(db, opts...),
		ArtifactVulnerability:         newArtifactVulnerability(db, opts...),
		Audit:                         newAudit(db, opts...),
		Blob:                          newBlob(db, opts...),
		BlobUpload:                    newBlobUpload(db, opts...),
		Builder:                       newBuilder(db, opts...),
		BuilderRunner:                 newBuilderRunner(db, opts...),
		CodeRepository:                newCodeRepository(db, opts...),
		CodeRepositoryBranch:          newCodeRepositoryBranch(db, opts...),
		CodeRepositoryCloneCredential: newCodeRepositoryCloneCredential(db, opts...),
		CodeRepositoryOwner:           newCodeRepositoryOwner(db, opts...),
		DaemonGcRecord:                newDaemonGcRecord(db, opts...),
		DaemonGcRule:                  newDaemonGcRule(db, opts...),
		DaemonGcRunner:                newDaemonGcRunner(db, opts...),
		Namespace:                     newNamespace(db, opts...),
		NamespaceActivityHourly:       newNamespaceActivityHourly(db, opts...),
		NamespaceMember:               newNamespaceMember(db, opts...),
		Repository:                    newRepository(db, opts...),
		Setting:                       newSetting(db, opts...),
		Tag:                           newTag(db, opts...),
		User:                          newUser(db, opts...),
		User3rdParty:                  newUser3rdParty(db, opts...),
		UserActivityHourly:            newUserActivityHourly(db, opts...),
		UserRecoverCode:               newUserRecoverCode(db, opts...),
		Webhook:                       newWebhook(db, opts...),
		WebhookLog:                    newWebhookLog(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Artifact                      artifact
	ArtifactSbom                  artifactSbom
	ArtifactVulnerability         artifactVulnerability
	Audit                         audit
	Blob                          blob
	BlobUpload                    blobUpload
	Builder                       builder
	BuilderRunner                 builderRunner
	CodeRepository                codeRepository
	CodeRepositoryBranch          codeRepositoryBranch
	CodeRepositoryCloneCredential codeRepositoryCloneCredential
	CodeRepositoryOwner           codeRepositoryOwner
	DaemonGcRecord                daemonGcRecord
	DaemonGcRule                  daemonGcRule
	DaemonGcRunner                daemonGcRunner
	Namespace                     namespace
	NamespaceActivityHourly       namespaceActivityHourly
	NamespaceMember               namespaceMember
	Repository                    repository
	Setting                       setting
	Tag                           tag
	User                          user
	User3rdParty                  user3rdParty
	UserActivityHourly            userActivityHourly
	UserRecoverCode               userRecoverCode
	Webhook                       webhook
	WebhookLog                    webhookLog
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                            db,
		Artifact:                      q.Artifact.clone(db),
		ArtifactSbom:                  q.ArtifactSbom.clone(db),
		ArtifactVulnerability:         q.ArtifactVulnerability.clone(db),
		Audit:                         q.Audit.clone(db),
		Blob:                          q.Blob.clone(db),
		BlobUpload:                    q.BlobUpload.clone(db),
		Builder:                       q.Builder.clone(db),
		BuilderRunner:                 q.BuilderRunner.clone(db),
		CodeRepository:                q.CodeRepository.clone(db),
		CodeRepositoryBranch:          q.CodeRepositoryBranch.clone(db),
		CodeRepositoryCloneCredential: q.CodeRepositoryCloneCredential.clone(db),
		CodeRepositoryOwner:           q.CodeRepositoryOwner.clone(db),
		DaemonGcRecord:                q.DaemonGcRecord.clone(db),
		DaemonGcRule:                  q.DaemonGcRule.clone(db),
		DaemonGcRunner:                q.DaemonGcRunner.clone(db),
		Namespace:                     q.Namespace.clone(db),
		NamespaceActivityHourly:       q.NamespaceActivityHourly.clone(db),
		NamespaceMember:               q.NamespaceMember.clone(db),
		Repository:                    q.Repository.clone(db),
		Setting:                       q.Setting.clone(db),
		Tag:                           q.Tag.clone(db),
		User:                          q.User.clone(db),
		User3rdParty:                  q.User3rdParty.clone(db),
		UserActivityHourly:            q.UserActivityHourly.clone(db),
		UserRecoverCode:               q.UserRecoverCode.clone(db),
		Webhook:                       q.Webhook.clone(db),
		WebhookLog:                    q.WebhookLog.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                            db,
		Artifact:                      q.Artifact.replaceDB(db),
		ArtifactSbom:                  q.ArtifactSbom.replaceDB(db),
		ArtifactVulnerability:         q.ArtifactVulnerability.replaceDB(db),
		Audit:                         q.Audit.replaceDB(db),
		Blob:                          q.Blob.replaceDB(db),
		BlobUpload:                    q.BlobUpload.replaceDB(db),
		Builder:                       q.Builder.replaceDB(db),
		BuilderRunner:                 q.BuilderRunner.replaceDB(db),
		CodeRepository:                q.CodeRepository.replaceDB(db),
		CodeRepositoryBranch:          q.CodeRepositoryBranch.replaceDB(db),
		CodeRepositoryCloneCredential: q.CodeRepositoryCloneCredential.replaceDB(db),
		CodeRepositoryOwner:           q.CodeRepositoryOwner.replaceDB(db),
		DaemonGcRecord:                q.DaemonGcRecord.replaceDB(db),
		DaemonGcRule:                  q.DaemonGcRule.replaceDB(db),
		DaemonGcRunner:                q.DaemonGcRunner.replaceDB(db),
		Namespace:                     q.Namespace.replaceDB(db),
		NamespaceActivityHourly:       q.NamespaceActivityHourly.replaceDB(db),
		NamespaceMember:               q.NamespaceMember.replaceDB(db),
		Repository:                    q.Repository.replaceDB(db),
		Setting:                       q.Setting.replaceDB(db),
		Tag:                           q.Tag.replaceDB(db),
		User:                          q.User.replaceDB(db),
		User3rdParty:                  q.User3rdParty.replaceDB(db),
		UserActivityHourly:            q.UserActivityHourly.replaceDB(db),
		UserRecoverCode:               q.UserRecoverCode.replaceDB(db),
		Webhook:                       q.Webhook.replaceDB(db),
		WebhookLog:                    q.WebhookLog.replaceDB(db),
	}
}

type queryCtx struct {
	Artifact                      *artifactDo
	ArtifactSbom                  *artifactSbomDo
	ArtifactVulnerability         *artifactVulnerabilityDo
	Audit                         *auditDo
	Blob                          *blobDo
	BlobUpload                    *blobUploadDo
	Builder                       *builderDo
	BuilderRunner                 *builderRunnerDo
	CodeRepository                *codeRepositoryDo
	CodeRepositoryBranch          *codeRepositoryBranchDo
	CodeRepositoryCloneCredential *codeRepositoryCloneCredentialDo
	CodeRepositoryOwner           *codeRepositoryOwnerDo
	DaemonGcRecord                *daemonGcRecordDo
	DaemonGcRule                  *daemonGcRuleDo
	DaemonGcRunner                *daemonGcRunnerDo
	Namespace                     *namespaceDo
	NamespaceActivityHourly       *namespaceActivityHourlyDo
	NamespaceMember               *namespaceMemberDo
	Repository                    *repositoryDo
	Setting                       *settingDo
	Tag                           *tagDo
	User                          *userDo
	User3rdParty                  *user3rdPartyDo
	UserActivityHourly            *userActivityHourlyDo
	UserRecoverCode               *userRecoverCodeDo
	Webhook                       *webhookDo
	WebhookLog                    *webhookLogDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Artifact:                      q.Artifact.WithContext(ctx),
		ArtifactSbom:                  q.ArtifactSbom.WithContext(ctx),
		ArtifactVulnerability:         q.ArtifactVulnerability.WithContext(ctx),
		Audit:                         q.Audit.WithContext(ctx),
		Blob:                          q.Blob.WithContext(ctx),
		BlobUpload:                    q.BlobUpload.WithContext(ctx),
		Builder:                       q.Builder.WithContext(ctx),
		BuilderRunner:                 q.BuilderRunner.WithContext(ctx),
		CodeRepository:                q.CodeRepository.WithContext(ctx),
		CodeRepositoryBranch:          q.CodeRepositoryBranch.WithContext(ctx),
		CodeRepositoryCloneCredential: q.CodeRepositoryCloneCredential.WithContext(ctx),
		CodeRepositoryOwner:           q.CodeRepositoryOwner.WithContext(ctx),
		DaemonGcRecord:                q.DaemonGcRecord.WithContext(ctx),
		DaemonGcRule:                  q.DaemonGcRule.WithContext(ctx),
		DaemonGcRunner:                q.DaemonGcRunner.WithContext(ctx),
		Namespace:                     q.Namespace.WithContext(ctx),
		NamespaceActivityHourly:       q.NamespaceActivityHourly.WithContext(ctx),
		NamespaceMember:               q.NamespaceMember.WithContext(ctx),
		Repository:                    q.Repository.WithContext(ctx),
		Setting:                       q.Setting.WithContext(ctx),
		Tag:                           q.Tag.WithContext(ctx),
		User:                          q.User.WithContext(ctx),
		User3rdParty:                  q.User3rdParty.WithContext(ctx),
		UserActivityHourly:            q.UserActivityHourly.WithContext(ctx),
		UserRecoverCode:               q.UserRecoverCode.WithContext(ctx),
		Webhook:                       q.Webhook.WithContext(ctx),
		WebhookLog:                    q.WebhookLog.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
