// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/ximager/ximager/pkg/dal/models"
)

func newProxyArtifactTaskBlob(db *gorm.DB, opts ...gen.DOOption) proxyArtifactTaskBlob {
	_proxyArtifactTaskBlob := proxyArtifactTaskBlob{}

	_proxyArtifactTaskBlob.proxyArtifactTaskBlobDo.UseDB(db, opts...)
	_proxyArtifactTaskBlob.proxyArtifactTaskBlobDo.UseModel(&models.ProxyArtifactTaskBlob{})

	tableName := _proxyArtifactTaskBlob.proxyArtifactTaskBlobDo.TableName()
	_proxyArtifactTaskBlob.ALL = field.NewAsterisk(tableName)
	_proxyArtifactTaskBlob.CreatedAt = field.NewTime(tableName, "created_at")
	_proxyArtifactTaskBlob.UpdatedAt = field.NewTime(tableName, "updated_at")
	_proxyArtifactTaskBlob.DeletedAt = field.NewUint(tableName, "deleted_at")
	_proxyArtifactTaskBlob.ID = field.NewUint64(tableName, "id")
	_proxyArtifactTaskBlob.ProxyArtifactTaskID = field.NewUint64(tableName, "proxy_artifact_task_id")
	_proxyArtifactTaskBlob.Blob = field.NewString(tableName, "blob")
	_proxyArtifactTaskBlob.ProxyArtifactTask = proxyArtifactTaskBlobBelongsToProxyArtifactTask{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ProxyArtifactTask", "models.ProxyArtifactTask"),
		Blobs: struct {
			field.RelationField
			ProxyArtifactTask struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("ProxyArtifactTask.Blobs", "models.ProxyArtifactTaskBlob"),
			ProxyArtifactTask: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ProxyArtifactTask.Blobs.ProxyArtifactTask", "models.ProxyArtifactTask"),
			},
		},
	}

	_proxyArtifactTaskBlob.fillFieldMap()

	return _proxyArtifactTaskBlob
}

type proxyArtifactTaskBlob struct {
	proxyArtifactTaskBlobDo proxyArtifactTaskBlobDo

	ALL                 field.Asterisk
	CreatedAt           field.Time
	UpdatedAt           field.Time
	DeletedAt           field.Uint
	ID                  field.Uint64
	ProxyArtifactTaskID field.Uint64
	Blob                field.String
	ProxyArtifactTask   proxyArtifactTaskBlobBelongsToProxyArtifactTask

	fieldMap map[string]field.Expr
}

func (p proxyArtifactTaskBlob) Table(newTableName string) *proxyArtifactTaskBlob {
	p.proxyArtifactTaskBlobDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p proxyArtifactTaskBlob) As(alias string) *proxyArtifactTaskBlob {
	p.proxyArtifactTaskBlobDo.DO = *(p.proxyArtifactTaskBlobDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *proxyArtifactTaskBlob) updateTableName(table string) *proxyArtifactTaskBlob {
	p.ALL = field.NewAsterisk(table)
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewUint(table, "deleted_at")
	p.ID = field.NewUint64(table, "id")
	p.ProxyArtifactTaskID = field.NewUint64(table, "proxy_artifact_task_id")
	p.Blob = field.NewString(table, "blob")

	p.fillFieldMap()

	return p
}

func (p *proxyArtifactTaskBlob) WithContext(ctx context.Context) *proxyArtifactTaskBlobDo {
	return p.proxyArtifactTaskBlobDo.WithContext(ctx)
}

func (p proxyArtifactTaskBlob) TableName() string { return p.proxyArtifactTaskBlobDo.TableName() }

func (p proxyArtifactTaskBlob) Alias() string { return p.proxyArtifactTaskBlobDo.Alias() }

func (p *proxyArtifactTaskBlob) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *proxyArtifactTaskBlob) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 7)
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["id"] = p.ID
	p.fieldMap["proxy_artifact_task_id"] = p.ProxyArtifactTaskID
	p.fieldMap["blob"] = p.Blob

}

func (p proxyArtifactTaskBlob) clone(db *gorm.DB) proxyArtifactTaskBlob {
	p.proxyArtifactTaskBlobDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p proxyArtifactTaskBlob) replaceDB(db *gorm.DB) proxyArtifactTaskBlob {
	p.proxyArtifactTaskBlobDo.ReplaceDB(db)
	return p
}

type proxyArtifactTaskBlobBelongsToProxyArtifactTask struct {
	db *gorm.DB

	field.RelationField

	Blobs struct {
		field.RelationField
		ProxyArtifactTask struct {
			field.RelationField
		}
	}
}

func (a proxyArtifactTaskBlobBelongsToProxyArtifactTask) Where(conds ...field.Expr) *proxyArtifactTaskBlobBelongsToProxyArtifactTask {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a proxyArtifactTaskBlobBelongsToProxyArtifactTask) WithContext(ctx context.Context) *proxyArtifactTaskBlobBelongsToProxyArtifactTask {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a proxyArtifactTaskBlobBelongsToProxyArtifactTask) Session(session *gorm.Session) *proxyArtifactTaskBlobBelongsToProxyArtifactTask {
	a.db = a.db.Session(session)
	return &a
}

func (a proxyArtifactTaskBlobBelongsToProxyArtifactTask) Model(m *models.ProxyArtifactTaskBlob) *proxyArtifactTaskBlobBelongsToProxyArtifactTaskTx {
	return &proxyArtifactTaskBlobBelongsToProxyArtifactTaskTx{a.db.Model(m).Association(a.Name())}
}

type proxyArtifactTaskBlobBelongsToProxyArtifactTaskTx struct{ tx *gorm.Association }

func (a proxyArtifactTaskBlobBelongsToProxyArtifactTaskTx) Find() (result *models.ProxyArtifactTask, err error) {
	return result, a.tx.Find(&result)
}

func (a proxyArtifactTaskBlobBelongsToProxyArtifactTaskTx) Append(values ...*models.ProxyArtifactTask) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a proxyArtifactTaskBlobBelongsToProxyArtifactTaskTx) Replace(values ...*models.ProxyArtifactTask) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a proxyArtifactTaskBlobBelongsToProxyArtifactTaskTx) Delete(values ...*models.ProxyArtifactTask) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a proxyArtifactTaskBlobBelongsToProxyArtifactTaskTx) Clear() error {
	return a.tx.Clear()
}

func (a proxyArtifactTaskBlobBelongsToProxyArtifactTaskTx) Count() int64 {
	return a.tx.Count()
}

type proxyArtifactTaskBlobDo struct{ gen.DO }

func (p proxyArtifactTaskBlobDo) Debug() *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Debug())
}

func (p proxyArtifactTaskBlobDo) WithContext(ctx context.Context) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p proxyArtifactTaskBlobDo) ReadDB() *proxyArtifactTaskBlobDo {
	return p.Clauses(dbresolver.Read)
}

func (p proxyArtifactTaskBlobDo) WriteDB() *proxyArtifactTaskBlobDo {
	return p.Clauses(dbresolver.Write)
}

func (p proxyArtifactTaskBlobDo) Session(config *gorm.Session) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Session(config))
}

func (p proxyArtifactTaskBlobDo) Clauses(conds ...clause.Expression) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p proxyArtifactTaskBlobDo) Returning(value interface{}, columns ...string) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p proxyArtifactTaskBlobDo) Not(conds ...gen.Condition) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p proxyArtifactTaskBlobDo) Or(conds ...gen.Condition) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p proxyArtifactTaskBlobDo) Select(conds ...field.Expr) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p proxyArtifactTaskBlobDo) Where(conds ...gen.Condition) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p proxyArtifactTaskBlobDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *proxyArtifactTaskBlobDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p proxyArtifactTaskBlobDo) Order(conds ...field.Expr) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p proxyArtifactTaskBlobDo) Distinct(cols ...field.Expr) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p proxyArtifactTaskBlobDo) Omit(cols ...field.Expr) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p proxyArtifactTaskBlobDo) Join(table schema.Tabler, on ...field.Expr) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p proxyArtifactTaskBlobDo) LeftJoin(table schema.Tabler, on ...field.Expr) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p proxyArtifactTaskBlobDo) RightJoin(table schema.Tabler, on ...field.Expr) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p proxyArtifactTaskBlobDo) Group(cols ...field.Expr) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p proxyArtifactTaskBlobDo) Having(conds ...gen.Condition) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p proxyArtifactTaskBlobDo) Limit(limit int) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p proxyArtifactTaskBlobDo) Offset(offset int) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p proxyArtifactTaskBlobDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p proxyArtifactTaskBlobDo) Unscoped() *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Unscoped())
}

func (p proxyArtifactTaskBlobDo) Create(values ...*models.ProxyArtifactTaskBlob) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p proxyArtifactTaskBlobDo) CreateInBatches(values []*models.ProxyArtifactTaskBlob, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p proxyArtifactTaskBlobDo) Save(values ...*models.ProxyArtifactTaskBlob) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p proxyArtifactTaskBlobDo) First() (*models.ProxyArtifactTaskBlob, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProxyArtifactTaskBlob), nil
	}
}

func (p proxyArtifactTaskBlobDo) Take() (*models.ProxyArtifactTaskBlob, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProxyArtifactTaskBlob), nil
	}
}

func (p proxyArtifactTaskBlobDo) Last() (*models.ProxyArtifactTaskBlob, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProxyArtifactTaskBlob), nil
	}
}

func (p proxyArtifactTaskBlobDo) Find() ([]*models.ProxyArtifactTaskBlob, error) {
	result, err := p.DO.Find()
	return result.([]*models.ProxyArtifactTaskBlob), err
}

func (p proxyArtifactTaskBlobDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ProxyArtifactTaskBlob, err error) {
	buf := make([]*models.ProxyArtifactTaskBlob, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p proxyArtifactTaskBlobDo) FindInBatches(result *[]*models.ProxyArtifactTaskBlob, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p proxyArtifactTaskBlobDo) Attrs(attrs ...field.AssignExpr) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p proxyArtifactTaskBlobDo) Assign(attrs ...field.AssignExpr) *proxyArtifactTaskBlobDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p proxyArtifactTaskBlobDo) Joins(fields ...field.RelationField) *proxyArtifactTaskBlobDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p proxyArtifactTaskBlobDo) Preload(fields ...field.RelationField) *proxyArtifactTaskBlobDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p proxyArtifactTaskBlobDo) FirstOrInit() (*models.ProxyArtifactTaskBlob, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProxyArtifactTaskBlob), nil
	}
}

func (p proxyArtifactTaskBlobDo) FirstOrCreate() (*models.ProxyArtifactTaskBlob, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ProxyArtifactTaskBlob), nil
	}
}

func (p proxyArtifactTaskBlobDo) FindByPage(offset int, limit int) (result []*models.ProxyArtifactTaskBlob, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p proxyArtifactTaskBlobDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p proxyArtifactTaskBlobDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p proxyArtifactTaskBlobDo) Delete(models ...*models.ProxyArtifactTaskBlob) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *proxyArtifactTaskBlobDo) withDO(do gen.Dao) *proxyArtifactTaskBlobDo {
	p.DO = *do.(*gen.DO)
	return p
}
