// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-sigma/sigma/pkg/service/coderepos (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -mock_names Service=MockCodeRepositoryService -destination=coderepos_mocks.go -package=coderepos github.com/go-sigma/sigma/pkg/service/coderepos Service
//

// Package coderepos is a generated GoMock package.
package coderepos

import (
	context "context"
	reflect "reflect"

	api "github.com/go-sigma/sigma/pkg/api"
	enums "github.com/go-sigma/sigma/pkg/api/enums"
	models "github.com/go-sigma/sigma/pkg/dal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCodeRepositoryService is a mock of Service interface.
type MockCodeRepositoryService struct {
	ctrl     *gomock.Controller
	recorder *MockCodeRepositoryServiceMockRecorder
	isgomock struct{}
}

// MockCodeRepositoryServiceMockRecorder is the mock recorder for MockCodeRepositoryService.
type MockCodeRepositoryServiceMockRecorder struct {
	mock *MockCodeRepositoryService
}

// NewMockCodeRepositoryService creates a new mock instance.
func NewMockCodeRepositoryService(ctrl *gomock.Controller) *MockCodeRepositoryService {
	mock := &MockCodeRepositoryService{ctrl: ctrl}
	mock.recorder = &MockCodeRepositoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeRepositoryService) EXPECT() *MockCodeRepositoryServiceMockRecorder {
	return m.recorder
}

// GetCodeRepository mocks base method.
func (m *MockCodeRepositoryService) GetCodeRepository(ctx context.Context, userID string, provider enums.Provider, id string) (*models.CodeRepository, []*models.CodeRepositoryOwner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCodeRepository", ctx, userID, provider, id)
	ret0, _ := ret[0].(*models.CodeRepository)
	ret1, _ := ret[1].([]*models.CodeRepositoryOwner)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCodeRepository indicates an expected call of GetCodeRepository.
func (mr *MockCodeRepositoryServiceMockRecorder) GetCodeRepository(ctx, userID, provider, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodeRepository", reflect.TypeOf((*MockCodeRepositoryService)(nil).GetCodeRepository), ctx, userID, provider, id)
}

// GetCodeRepositoryBranch mocks base method.
func (m *MockCodeRepositoryService) GetCodeRepositoryBranch(ctx context.Context, codeRepositoryID, name string) (*models.CodeRepositoryBranch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCodeRepositoryBranch", ctx, codeRepositoryID, name)
	ret0, _ := ret[0].(*models.CodeRepositoryBranch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCodeRepositoryBranch indicates an expected call of GetCodeRepositoryBranch.
func (mr *MockCodeRepositoryServiceMockRecorder) GetCodeRepositoryBranch(ctx, codeRepositoryID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodeRepositoryBranch", reflect.TypeOf((*MockCodeRepositoryService)(nil).GetCodeRepositoryBranch), ctx, codeRepositoryID, name)
}

// GetCodeRepositoryUser3rdParty mocks base method.
func (m *MockCodeRepositoryService) GetCodeRepositoryUser3rdParty(ctx context.Context, userID string, provider enums.Provider) (*models.User3rdParty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCodeRepositoryUser3rdParty", ctx, userID, provider)
	ret0, _ := ret[0].(*models.User3rdParty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCodeRepositoryUser3rdParty indicates an expected call of GetCodeRepositoryUser3rdParty.
func (mr *MockCodeRepositoryServiceMockRecorder) GetCodeRepositoryUser3rdParty(ctx, userID, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCodeRepositoryUser3rdParty", reflect.TypeOf((*MockCodeRepositoryService)(nil).GetCodeRepositoryUser3rdParty), ctx, userID, provider)
}

// ListCodeRepositories mocks base method.
func (m *MockCodeRepositoryService) ListCodeRepositories(ctx context.Context, userID string, provider enums.Provider, owner, name *string, pagination api.Pagination, sort api.Sortable) ([]*models.CodeRepository, []*models.CodeRepositoryOwner, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCodeRepositories", ctx, userID, provider, owner, name, pagination, sort)
	ret0, _ := ret[0].([]*models.CodeRepository)
	ret1, _ := ret[1].([]*models.CodeRepositoryOwner)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListCodeRepositories indicates an expected call of ListCodeRepositories.
func (mr *MockCodeRepositoryServiceMockRecorder) ListCodeRepositories(ctx, userID, provider, owner, name, pagination, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCodeRepositories", reflect.TypeOf((*MockCodeRepositoryService)(nil).ListCodeRepositories), ctx, userID, provider, owner, name, pagination, sort)
}

// ListCodeRepositoryBranches mocks base method.
func (m *MockCodeRepositoryService) ListCodeRepositoryBranches(ctx context.Context, codeRepositoryID string) ([]*models.CodeRepositoryBranch, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCodeRepositoryBranches", ctx, codeRepositoryID)
	ret0, _ := ret[0].([]*models.CodeRepositoryBranch)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCodeRepositoryBranches indicates an expected call of ListCodeRepositoryBranches.
func (mr *MockCodeRepositoryServiceMockRecorder) ListCodeRepositoryBranches(ctx, codeRepositoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCodeRepositoryBranches", reflect.TypeOf((*MockCodeRepositoryService)(nil).ListCodeRepositoryBranches), ctx, codeRepositoryID)
}

// ListCodeRepositoryOwners mocks base method.
func (m *MockCodeRepositoryService) ListCodeRepositoryOwners(ctx context.Context, userID string, provider enums.Provider, name *string) ([]*models.CodeRepositoryOwner, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCodeRepositoryOwners", ctx, userID, provider, name)
	ret0, _ := ret[0].([]*models.CodeRepositoryOwner)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCodeRepositoryOwners indicates an expected call of ListCodeRepositoryOwners.
func (mr *MockCodeRepositoryServiceMockRecorder) ListCodeRepositoryOwners(ctx, userID, provider, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCodeRepositoryOwners", reflect.TypeOf((*MockCodeRepositoryService)(nil).ListCodeRepositoryOwners), ctx, userID, provider, name)
}

// ListCodeRepositoryProviders mocks base method.
func (m *MockCodeRepositoryService) ListCodeRepositoryProviders(ctx context.Context, userID string) ([]*models.User3rdParty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCodeRepositoryProviders", ctx, userID)
	ret0, _ := ret[0].([]*models.User3rdParty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCodeRepositoryProviders indicates an expected call of ListCodeRepositoryProviders.
func (mr *MockCodeRepositoryServiceMockRecorder) ListCodeRepositoryProviders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCodeRepositoryProviders", reflect.TypeOf((*MockCodeRepositoryService)(nil).ListCodeRepositoryProviders), ctx, userID)
}

// ResyncCodeRepositories mocks base method.
func (m *MockCodeRepositoryService) ResyncCodeRepositories(ctx context.Context, userID string, provider enums.Provider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResyncCodeRepositories", ctx, userID, provider)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResyncCodeRepositories indicates an expected call of ResyncCodeRepositories.
func (mr *MockCodeRepositoryServiceMockRecorder) ResyncCodeRepositories(ctx, userID, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResyncCodeRepositories", reflect.TypeOf((*MockCodeRepositoryService)(nil).ResyncCodeRepositories), ctx, userID, provider)
}
