// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-sigma/sigma/pkg/service/webhooks (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -mock_names Service=MockWebhookService -destination=webhooks_mocks.go -package=webhooks github.com/go-sigma/sigma/pkg/service/webhooks Service
//

// Package webhooks is a generated GoMock package.
package webhooks

import (
	context "context"
	reflect "reflect"

	api "github.com/go-sigma/sigma/pkg/api"
	models "github.com/go-sigma/sigma/pkg/dal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookService is a mock of Service interface.
type MockWebhookService struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookServiceMockRecorder
	isgomock struct{}
}

// MockWebhookServiceMockRecorder is the mock recorder for MockWebhookService.
type MockWebhookServiceMockRecorder struct {
	mock *MockWebhookService
}

// NewMockWebhookService creates a new mock instance.
func NewMockWebhookService(ctrl *gomock.Controller) *MockWebhookService {
	mock := &MockWebhookService{ctrl: ctrl}
	mock.recorder = &MockWebhookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookService) EXPECT() *MockWebhookServiceMockRecorder {
	return m.recorder
}

// CreateWebhook mocks base method.
func (m *MockWebhookService) CreateWebhook(ctx context.Context, userID string, req api.PostWebhookRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebhook", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWebhook indicates an expected call of CreateWebhook.
func (mr *MockWebhookServiceMockRecorder) CreateWebhook(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebhook", reflect.TypeOf((*MockWebhookService)(nil).CreateWebhook), ctx, userID, req)
}

// DeleteWebhook mocks base method.
func (m *MockWebhookService) DeleteWebhook(ctx context.Context, userID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebhook", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWebhook indicates an expected call of DeleteWebhook.
func (mr *MockWebhookServiceMockRecorder) DeleteWebhook(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebhook", reflect.TypeOf((*MockWebhookService)(nil).DeleteWebhook), ctx, userID, id)
}

// DeleteWebhookLog mocks base method.
func (m *MockWebhookService) DeleteWebhookLog(ctx context.Context, userID, webhookID, webhookLogID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebhookLog", ctx, userID, webhookID, webhookLogID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWebhookLog indicates an expected call of DeleteWebhookLog.
func (mr *MockWebhookServiceMockRecorder) DeleteWebhookLog(ctx, userID, webhookID, webhookLogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebhookLog", reflect.TypeOf((*MockWebhookService)(nil).DeleteWebhookLog), ctx, userID, webhookID, webhookLogID)
}

// GetWebhook mocks base method.
func (m *MockWebhookService) GetWebhook(ctx context.Context, id string) (*models.Webhook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhook", ctx, id)
	ret0, _ := ret[0].(*models.Webhook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhook indicates an expected call of GetWebhook.
func (mr *MockWebhookServiceMockRecorder) GetWebhook(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhook", reflect.TypeOf((*MockWebhookService)(nil).GetWebhook), ctx, id)
}

// GetWebhookLog mocks base method.
func (m *MockWebhookService) GetWebhookLog(ctx context.Context, webhookLogID string) (*models.WebhookLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookLog", ctx, webhookLogID)
	ret0, _ := ret[0].(*models.WebhookLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookLog indicates an expected call of GetWebhookLog.
func (mr *MockWebhookServiceMockRecorder) GetWebhookLog(ctx, webhookLogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookLog", reflect.TypeOf((*MockWebhookService)(nil).GetWebhookLog), ctx, webhookLogID)
}

// ListWebhookLogs mocks base method.
func (m *MockWebhookService) ListWebhookLogs(ctx context.Context, webhookID string, pagination api.Pagination, sort api.Sortable) ([]*models.WebhookLog, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWebhookLogs", ctx, webhookID, pagination, sort)
	ret0, _ := ret[0].([]*models.WebhookLog)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListWebhookLogs indicates an expected call of ListWebhookLogs.
func (mr *MockWebhookServiceMockRecorder) ListWebhookLogs(ctx, webhookID, pagination, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWebhookLogs", reflect.TypeOf((*MockWebhookService)(nil).ListWebhookLogs), ctx, webhookID, pagination, sort)
}

// ListWebhooks mocks base method.
func (m *MockWebhookService) ListWebhooks(ctx context.Context, namespaceID *string, pagination api.Pagination, sort api.Sortable) ([]*models.Webhook, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWebhooks", ctx, namespaceID, pagination, sort)
	ret0, _ := ret[0].([]*models.Webhook)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListWebhooks indicates an expected call of ListWebhooks.
func (mr *MockWebhookServiceMockRecorder) ListWebhooks(ctx, namespaceID, pagination, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWebhooks", reflect.TypeOf((*MockWebhookService)(nil).ListWebhooks), ctx, namespaceID, pagination, sort)
}

// PingWebhook mocks base method.
func (m *MockWebhookService) PingWebhook(ctx context.Context, userID, webhookID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingWebhook", ctx, userID, webhookID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingWebhook indicates an expected call of PingWebhook.
func (mr *MockWebhookServiceMockRecorder) PingWebhook(ctx, userID, webhookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingWebhook", reflect.TypeOf((*MockWebhookService)(nil).PingWebhook), ctx, userID, webhookID)
}

// ResendWebhookLog mocks base method.
func (m *MockWebhookService) ResendWebhookLog(ctx context.Context, userID, webhookID, webhookLogID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResendWebhookLog", ctx, userID, webhookID, webhookLogID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResendWebhookLog indicates an expected call of ResendWebhookLog.
func (mr *MockWebhookServiceMockRecorder) ResendWebhookLog(ctx, userID, webhookID, webhookLogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendWebhookLog", reflect.TypeOf((*MockWebhookService)(nil).ResendWebhookLog), ctx, userID, webhookID, webhookLogID)
}

// UpdateWebhook mocks base method.
func (m *MockWebhookService) UpdateWebhook(ctx context.Context, userID, id string, req api.PutWebhookRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebhook", ctx, userID, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWebhook indicates an expected call of UpdateWebhook.
func (mr *MockWebhookServiceMockRecorder) UpdateWebhook(ctx, userID, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebhook", reflect.TypeOf((*MockWebhookService)(nil).UpdateWebhook), ctx, userID, id, req)
}
