// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-sigma/sigma/pkg/service/daemons (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -mock_names Service=MockDaemonService -destination=daemons_mocks.go -package=daemons github.com/go-sigma/sigma/pkg/service/daemons Service
//

// Package daemons is a generated GoMock package.
package daemons

import (
	context "context"
	reflect "reflect"

	api "github.com/go-sigma/sigma/pkg/api"
	models "github.com/go-sigma/sigma/pkg/dal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockDaemonService is a mock of Service interface.
type MockDaemonService struct {
	ctrl     *gomock.Controller
	recorder *MockDaemonServiceMockRecorder
	isgomock struct{}
}

// MockDaemonServiceMockRecorder is the mock recorder for MockDaemonService.
type MockDaemonServiceMockRecorder struct {
	mock *MockDaemonService
}

// NewMockDaemonService creates a new mock instance.
func NewMockDaemonService(ctrl *gomock.Controller) *MockDaemonService {
	mock := &MockDaemonService{ctrl: ctrl}
	mock.recorder = &MockDaemonServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaemonService) EXPECT() *MockDaemonServiceMockRecorder {
	return m.recorder
}

// CreateGcArtifactRunner mocks base method.
func (m *MockDaemonService) CreateGcArtifactRunner(ctx context.Context, req api.CreateGcArtifactRunnerRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGcArtifactRunner", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGcArtifactRunner indicates an expected call of CreateGcArtifactRunner.
func (mr *MockDaemonServiceMockRecorder) CreateGcArtifactRunner(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGcArtifactRunner", reflect.TypeOf((*MockDaemonService)(nil).CreateGcArtifactRunner), ctx, req)
}

// CreateGcBlobRunner mocks base method.
func (m *MockDaemonService) CreateGcBlobRunner(ctx context.Context, userID string, req api.CreateGcBlobRunnerRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGcBlobRunner", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGcBlobRunner indicates an expected call of CreateGcBlobRunner.
func (mr *MockDaemonServiceMockRecorder) CreateGcBlobRunner(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGcBlobRunner", reflect.TypeOf((*MockDaemonService)(nil).CreateGcBlobRunner), ctx, userID, req)
}

// CreateGcRepositoryRunner mocks base method.
func (m *MockDaemonService) CreateGcRepositoryRunner(ctx context.Context, req api.CreateGcRepositoryRunnerRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGcRepositoryRunner", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGcRepositoryRunner indicates an expected call of CreateGcRepositoryRunner.
func (mr *MockDaemonServiceMockRecorder) CreateGcRepositoryRunner(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGcRepositoryRunner", reflect.TypeOf((*MockDaemonService)(nil).CreateGcRepositoryRunner), ctx, req)
}

// CreateGcTagRunner mocks base method.
func (m *MockDaemonService) CreateGcTagRunner(ctx context.Context, req api.CreateGcTagRunnerRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGcTagRunner", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateGcTagRunner indicates an expected call of CreateGcTagRunner.
func (mr *MockDaemonServiceMockRecorder) CreateGcTagRunner(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGcTagRunner", reflect.TypeOf((*MockDaemonService)(nil).CreateGcTagRunner), ctx, req)
}

// GetGcArtifactLatestRunner mocks base method.
func (m *MockDaemonService) GetGcArtifactLatestRunner(ctx context.Context, namespaceID string) (*models.DaemonGcArtifactRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcArtifactLatestRunner", ctx, namespaceID)
	ret0, _ := ret[0].(*models.DaemonGcArtifactRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcArtifactLatestRunner indicates an expected call of GetGcArtifactLatestRunner.
func (mr *MockDaemonServiceMockRecorder) GetGcArtifactLatestRunner(ctx, namespaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcArtifactLatestRunner", reflect.TypeOf((*MockDaemonService)(nil).GetGcArtifactLatestRunner), ctx, namespaceID)
}

// GetGcArtifactRecord mocks base method.
func (m *MockDaemonService) GetGcArtifactRecord(ctx context.Context, namespaceID, runnerID, recordID string) (*models.DaemonGcArtifactRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcArtifactRecord", ctx, namespaceID, runnerID, recordID)
	ret0, _ := ret[0].(*models.DaemonGcArtifactRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcArtifactRecord indicates an expected call of GetGcArtifactRecord.
func (mr *MockDaemonServiceMockRecorder) GetGcArtifactRecord(ctx, namespaceID, runnerID, recordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcArtifactRecord", reflect.TypeOf((*MockDaemonService)(nil).GetGcArtifactRecord), ctx, namespaceID, runnerID, recordID)
}

// GetGcArtifactRule mocks base method.
func (m *MockDaemonService) GetGcArtifactRule(ctx context.Context, namespaceID string) (*models.DaemonGcArtifactRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcArtifactRule", ctx, namespaceID)
	ret0, _ := ret[0].(*models.DaemonGcArtifactRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcArtifactRule indicates an expected call of GetGcArtifactRule.
func (mr *MockDaemonServiceMockRecorder) GetGcArtifactRule(ctx, namespaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcArtifactRule", reflect.TypeOf((*MockDaemonService)(nil).GetGcArtifactRule), ctx, namespaceID)
}

// GetGcArtifactRunner mocks base method.
func (m *MockDaemonService) GetGcArtifactRunner(ctx context.Context, namespaceID, runnerID string) (*models.DaemonGcArtifactRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcArtifactRunner", ctx, namespaceID, runnerID)
	ret0, _ := ret[0].(*models.DaemonGcArtifactRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcArtifactRunner indicates an expected call of GetGcArtifactRunner.
func (mr *MockDaemonServiceMockRecorder) GetGcArtifactRunner(ctx, namespaceID, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcArtifactRunner", reflect.TypeOf((*MockDaemonService)(nil).GetGcArtifactRunner), ctx, namespaceID, runnerID)
}

// GetGcBlobLatestRunner mocks base method.
func (m *MockDaemonService) GetGcBlobLatestRunner(ctx context.Context, namespaceID string) (*models.DaemonGcBlobRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcBlobLatestRunner", ctx, namespaceID)
	ret0, _ := ret[0].(*models.DaemonGcBlobRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcBlobLatestRunner indicates an expected call of GetGcBlobLatestRunner.
func (mr *MockDaemonServiceMockRecorder) GetGcBlobLatestRunner(ctx, namespaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcBlobLatestRunner", reflect.TypeOf((*MockDaemonService)(nil).GetGcBlobLatestRunner), ctx, namespaceID)
}

// GetGcBlobRecord mocks base method.
func (m *MockDaemonService) GetGcBlobRecord(ctx context.Context, runnerID, recordID string) (*models.DaemonGcBlobRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcBlobRecord", ctx, runnerID, recordID)
	ret0, _ := ret[0].(*models.DaemonGcBlobRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcBlobRecord indicates an expected call of GetGcBlobRecord.
func (mr *MockDaemonServiceMockRecorder) GetGcBlobRecord(ctx, runnerID, recordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcBlobRecord", reflect.TypeOf((*MockDaemonService)(nil).GetGcBlobRecord), ctx, runnerID, recordID)
}

// GetGcBlobRule mocks base method.
func (m *MockDaemonService) GetGcBlobRule(ctx context.Context) (*models.DaemonGcBlobRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcBlobRule", ctx)
	ret0, _ := ret[0].(*models.DaemonGcBlobRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcBlobRule indicates an expected call of GetGcBlobRule.
func (mr *MockDaemonServiceMockRecorder) GetGcBlobRule(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcBlobRule", reflect.TypeOf((*MockDaemonService)(nil).GetGcBlobRule), ctx)
}

// GetGcBlobRunner mocks base method.
func (m *MockDaemonService) GetGcBlobRunner(ctx context.Context, runnerID string) (*models.DaemonGcBlobRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcBlobRunner", ctx, runnerID)
	ret0, _ := ret[0].(*models.DaemonGcBlobRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcBlobRunner indicates an expected call of GetGcBlobRunner.
func (mr *MockDaemonServiceMockRecorder) GetGcBlobRunner(ctx, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcBlobRunner", reflect.TypeOf((*MockDaemonService)(nil).GetGcBlobRunner), ctx, runnerID)
}

// GetGcRepositoryLatestRunner mocks base method.
func (m *MockDaemonService) GetGcRepositoryLatestRunner(ctx context.Context, namespaceID string) (*models.DaemonGcRepositoryRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcRepositoryLatestRunner", ctx, namespaceID)
	ret0, _ := ret[0].(*models.DaemonGcRepositoryRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcRepositoryLatestRunner indicates an expected call of GetGcRepositoryLatestRunner.
func (mr *MockDaemonServiceMockRecorder) GetGcRepositoryLatestRunner(ctx, namespaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcRepositoryLatestRunner", reflect.TypeOf((*MockDaemonService)(nil).GetGcRepositoryLatestRunner), ctx, namespaceID)
}

// GetGcRepositoryRecord mocks base method.
func (m *MockDaemonService) GetGcRepositoryRecord(ctx context.Context, namespaceID, runnerID, recordID string) (*models.DaemonGcRepositoryRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcRepositoryRecord", ctx, namespaceID, runnerID, recordID)
	ret0, _ := ret[0].(*models.DaemonGcRepositoryRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcRepositoryRecord indicates an expected call of GetGcRepositoryRecord.
func (mr *MockDaemonServiceMockRecorder) GetGcRepositoryRecord(ctx, namespaceID, runnerID, recordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcRepositoryRecord", reflect.TypeOf((*MockDaemonService)(nil).GetGcRepositoryRecord), ctx, namespaceID, runnerID, recordID)
}

// GetGcRepositoryRule mocks base method.
func (m *MockDaemonService) GetGcRepositoryRule(ctx context.Context, namespaceID string) (*models.DaemonGcRepositoryRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcRepositoryRule", ctx, namespaceID)
	ret0, _ := ret[0].(*models.DaemonGcRepositoryRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcRepositoryRule indicates an expected call of GetGcRepositoryRule.
func (mr *MockDaemonServiceMockRecorder) GetGcRepositoryRule(ctx, namespaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcRepositoryRule", reflect.TypeOf((*MockDaemonService)(nil).GetGcRepositoryRule), ctx, namespaceID)
}

// GetGcRepositoryRunner mocks base method.
func (m *MockDaemonService) GetGcRepositoryRunner(ctx context.Context, namespaceID, runnerID string) (*models.DaemonGcRepositoryRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcRepositoryRunner", ctx, namespaceID, runnerID)
	ret0, _ := ret[0].(*models.DaemonGcRepositoryRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcRepositoryRunner indicates an expected call of GetGcRepositoryRunner.
func (mr *MockDaemonServiceMockRecorder) GetGcRepositoryRunner(ctx, namespaceID, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcRepositoryRunner", reflect.TypeOf((*MockDaemonService)(nil).GetGcRepositoryRunner), ctx, namespaceID, runnerID)
}

// GetGcTagLatestRunner mocks base method.
func (m *MockDaemonService) GetGcTagLatestRunner(ctx context.Context, namespaceID string) (*models.DaemonGcTagRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcTagLatestRunner", ctx, namespaceID)
	ret0, _ := ret[0].(*models.DaemonGcTagRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcTagLatestRunner indicates an expected call of GetGcTagLatestRunner.
func (mr *MockDaemonServiceMockRecorder) GetGcTagLatestRunner(ctx, namespaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcTagLatestRunner", reflect.TypeOf((*MockDaemonService)(nil).GetGcTagLatestRunner), ctx, namespaceID)
}

// GetGcTagRecord mocks base method.
func (m *MockDaemonService) GetGcTagRecord(ctx context.Context, namespaceID, runnerID, recordID string) (*models.DaemonGcTagRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcTagRecord", ctx, namespaceID, runnerID, recordID)
	ret0, _ := ret[0].(*models.DaemonGcTagRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcTagRecord indicates an expected call of GetGcTagRecord.
func (mr *MockDaemonServiceMockRecorder) GetGcTagRecord(ctx, namespaceID, runnerID, recordID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcTagRecord", reflect.TypeOf((*MockDaemonService)(nil).GetGcTagRecord), ctx, namespaceID, runnerID, recordID)
}

// GetGcTagRule mocks base method.
func (m *MockDaemonService) GetGcTagRule(ctx context.Context, namespaceID string) (*models.DaemonGcTagRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcTagRule", ctx, namespaceID)
	ret0, _ := ret[0].(*models.DaemonGcTagRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcTagRule indicates an expected call of GetGcTagRule.
func (mr *MockDaemonServiceMockRecorder) GetGcTagRule(ctx, namespaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcTagRule", reflect.TypeOf((*MockDaemonService)(nil).GetGcTagRule), ctx, namespaceID)
}

// GetGcTagRunner mocks base method.
func (m *MockDaemonService) GetGcTagRunner(ctx context.Context, namespaceID, runnerID string) (*models.DaemonGcTagRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGcTagRunner", ctx, namespaceID, runnerID)
	ret0, _ := ret[0].(*models.DaemonGcTagRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGcTagRunner indicates an expected call of GetGcTagRunner.
func (mr *MockDaemonServiceMockRecorder) GetGcTagRunner(ctx, namespaceID, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGcTagRunner", reflect.TypeOf((*MockDaemonService)(nil).GetGcTagRunner), ctx, namespaceID, runnerID)
}

// ListGcArtifactRecords mocks base method.
func (m *MockDaemonService) ListGcArtifactRecords(ctx context.Context, runnerID string, pagination api.Pagination, sort api.Sortable) ([]*models.DaemonGcArtifactRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGcArtifactRecords", ctx, runnerID, pagination, sort)
	ret0, _ := ret[0].([]*models.DaemonGcArtifactRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGcArtifactRecords indicates an expected call of ListGcArtifactRecords.
func (mr *MockDaemonServiceMockRecorder) ListGcArtifactRecords(ctx, runnerID, pagination, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGcArtifactRecords", reflect.TypeOf((*MockDaemonService)(nil).ListGcArtifactRecords), ctx, runnerID, pagination, sort)
}

// ListGcArtifactRunners mocks base method.
func (m *MockDaemonService) ListGcArtifactRunners(ctx context.Context, namespaceID string, pagination api.Pagination, sort api.Sortable) ([]*models.DaemonGcArtifactRunner, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGcArtifactRunners", ctx, namespaceID, pagination, sort)
	ret0, _ := ret[0].([]*models.DaemonGcArtifactRunner)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGcArtifactRunners indicates an expected call of ListGcArtifactRunners.
func (mr *MockDaemonServiceMockRecorder) ListGcArtifactRunners(ctx, namespaceID, pagination, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGcArtifactRunners", reflect.TypeOf((*MockDaemonService)(nil).ListGcArtifactRunners), ctx, namespaceID, pagination, sort)
}

// ListGcBlobRecords mocks base method.
func (m *MockDaemonService) ListGcBlobRecords(ctx context.Context, runnerID string, pagination api.Pagination, sort api.Sortable) ([]*models.DaemonGcBlobRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGcBlobRecords", ctx, runnerID, pagination, sort)
	ret0, _ := ret[0].([]*models.DaemonGcBlobRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGcBlobRecords indicates an expected call of ListGcBlobRecords.
func (mr *MockDaemonServiceMockRecorder) ListGcBlobRecords(ctx, runnerID, pagination, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGcBlobRecords", reflect.TypeOf((*MockDaemonService)(nil).ListGcBlobRecords), ctx, runnerID, pagination, sort)
}

// ListGcBlobRunners mocks base method.
func (m *MockDaemonService) ListGcBlobRunners(ctx context.Context, pagination api.Pagination, sort api.Sortable) ([]*models.DaemonGcBlobRunner, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGcBlobRunners", ctx, pagination, sort)
	ret0, _ := ret[0].([]*models.DaemonGcBlobRunner)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGcBlobRunners indicates an expected call of ListGcBlobRunners.
func (mr *MockDaemonServiceMockRecorder) ListGcBlobRunners(ctx, pagination, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGcBlobRunners", reflect.TypeOf((*MockDaemonService)(nil).ListGcBlobRunners), ctx, pagination, sort)
}

// ListGcRepositoryRecords mocks base method.
func (m *MockDaemonService) ListGcRepositoryRecords(ctx context.Context, runnerID string, pagination api.Pagination, sort api.Sortable) ([]*models.DaemonGcRepositoryRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGcRepositoryRecords", ctx, runnerID, pagination, sort)
	ret0, _ := ret[0].([]*models.DaemonGcRepositoryRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGcRepositoryRecords indicates an expected call of ListGcRepositoryRecords.
func (mr *MockDaemonServiceMockRecorder) ListGcRepositoryRecords(ctx, runnerID, pagination, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGcRepositoryRecords", reflect.TypeOf((*MockDaemonService)(nil).ListGcRepositoryRecords), ctx, runnerID, pagination, sort)
}

// ListGcRepositoryRunners mocks base method.
func (m *MockDaemonService) ListGcRepositoryRunners(ctx context.Context, namespaceID string, pagination api.Pagination, sort api.Sortable) ([]*models.DaemonGcRepositoryRunner, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGcRepositoryRunners", ctx, namespaceID, pagination, sort)
	ret0, _ := ret[0].([]*models.DaemonGcRepositoryRunner)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGcRepositoryRunners indicates an expected call of ListGcRepositoryRunners.
func (mr *MockDaemonServiceMockRecorder) ListGcRepositoryRunners(ctx, namespaceID, pagination, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGcRepositoryRunners", reflect.TypeOf((*MockDaemonService)(nil).ListGcRepositoryRunners), ctx, namespaceID, pagination, sort)
}

// ListGcTagRecords mocks base method.
func (m *MockDaemonService) ListGcTagRecords(ctx context.Context, runnerID string, pagination api.Pagination, sort api.Sortable) ([]*models.DaemonGcTagRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGcTagRecords", ctx, runnerID, pagination, sort)
	ret0, _ := ret[0].([]*models.DaemonGcTagRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGcTagRecords indicates an expected call of ListGcTagRecords.
func (mr *MockDaemonServiceMockRecorder) ListGcTagRecords(ctx, runnerID, pagination, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGcTagRecords", reflect.TypeOf((*MockDaemonService)(nil).ListGcTagRecords), ctx, runnerID, pagination, sort)
}

// ListGcTagRunners mocks base method.
func (m *MockDaemonService) ListGcTagRunners(ctx context.Context, namespaceID string, pagination api.Pagination, sort api.Sortable) ([]*models.DaemonGcTagRunner, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGcTagRunners", ctx, namespaceID, pagination, sort)
	ret0, _ := ret[0].([]*models.DaemonGcTagRunner)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListGcTagRunners indicates an expected call of ListGcTagRunners.
func (mr *MockDaemonServiceMockRecorder) ListGcTagRunners(ctx, namespaceID, pagination, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGcTagRunners", reflect.TypeOf((*MockDaemonService)(nil).ListGcTagRunners), ctx, namespaceID, pagination, sort)
}

// UpdateGcArtifactRule mocks base method.
func (m *MockDaemonService) UpdateGcArtifactRule(ctx context.Context, req api.UpdateGcArtifactRuleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGcArtifactRule", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGcArtifactRule indicates an expected call of UpdateGcArtifactRule.
func (mr *MockDaemonServiceMockRecorder) UpdateGcArtifactRule(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGcArtifactRule", reflect.TypeOf((*MockDaemonService)(nil).UpdateGcArtifactRule), ctx, req)
}

// UpdateGcBlobRule mocks base method.
func (m *MockDaemonService) UpdateGcBlobRule(ctx context.Context, req api.UpdateGcBlobRuleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGcBlobRule", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGcBlobRule indicates an expected call of UpdateGcBlobRule.
func (mr *MockDaemonServiceMockRecorder) UpdateGcBlobRule(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGcBlobRule", reflect.TypeOf((*MockDaemonService)(nil).UpdateGcBlobRule), ctx, req)
}

// UpdateGcRepositoryRule mocks base method.
func (m *MockDaemonService) UpdateGcRepositoryRule(ctx context.Context, req api.UpdateGcRepositoryRuleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGcRepositoryRule", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGcRepositoryRule indicates an expected call of UpdateGcRepositoryRule.
func (mr *MockDaemonServiceMockRecorder) UpdateGcRepositoryRule(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGcRepositoryRule", reflect.TypeOf((*MockDaemonService)(nil).UpdateGcRepositoryRule), ctx, req)
}

// UpdateGcTagRule mocks base method.
func (m *MockDaemonService) UpdateGcTagRule(ctx context.Context, req api.UpdateGcTagRuleRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGcTagRule", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGcTagRule indicates an expected call of UpdateGcTagRule.
func (mr *MockDaemonServiceMockRecorder) UpdateGcTagRule(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGcTagRule", reflect.TypeOf((*MockDaemonService)(nil).UpdateGcTagRule), ctx, req)
}
