apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sigma.server" . }}
  labels:
    {{- include "sigma.server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.autoscaling.replicaCount.server }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sigma.server.labels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sigma.server.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ printf "%s-server" .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - sigma
          args:
            - server
            - --without-distribution
            - --without-worker
            - --config=/etc/sigma/config.yaml
          ports:
            - name: http
              containerPort: {{ .Values.service.server.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.server.port }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.server.port }}
          volumeMounts:
            - name: config
              mountPath: "/etc/sigma/config.yaml"
              subPath: "config.yaml"
              readOnly: true
            # - name: trivy
            #   mountPath: "/opt/trivy-tmp"
              # TODO: image volumes not support subPath
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ printf "%s-config" .Chart.Name }}
        {{- if semverCompare ">= 1.31" .Capabilities.KubeVersion.Version }}
        - name: trivy
          image:
            reference: "{{ .Values.image.registry }}/{{ .Values.image.trivyRepository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            pullPolicy: {{ .Values.image.pullPolicy | quote }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
