apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configmap" .Chart.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "sigma.labels" . | nindent 4 }}
data:
  {{- if eq .Values.middleware.type "internal" }}
  config.yaml: |-
    log:
      level: debug
    database:
      type: mysql
      sqlite3:
        path: {{ .Chart.Name }}.db
      mysql:
        host: {{ .Release.Name }}-mysql
        port: 3306
        user: sigma
        password: sigma
        dbname: sigma
      postgresql:
        host: localhost
        port: 5432
        user: sigma
        password: sigma
        dbname: sigma
        sslmode: disable
    redis:
      url: redis://:sigma@{{ .Release.Name }}-redis-master:6379/0
    http:
      server: 0.0.0.0:3000
      worker: 0.0.0.0:3001
    daemon:
      gc:
        # if blob not associate with artifact
        retention: 72h
        # At 02:00 on Saturday
        cron: 0 2 * * 6
    storage:
      rootdirectory: ./storage
      type: s3
      filesystem:
        path: /
      s3:
        ak: sigma
        sk: sigma-sigma
        endpoint: http://{{ .Release.Name }}-minio:9000
        region: cn-north-1
        bucket: sigma
        forcePathStyle: true
    proxy:
      enabled: true
      endpoint: https://registry-1.docker.io
      tlsVerify: true
      username: ""
      password: ""
    auth:
      user:
        password: ""
      internalUser:
        username: internal-sigma
        password: internal-sigma
      admin:
        username: sigma
        password: sigma
      token:
        realm: ""
        service: ""
      jwt:
        ttl: 1h
        refreshTtl: 24h
        privateKey: {{ genPrivateKey "rsa" | b64enc }}
  {{- else if eq .Values.middleware.type "external" }}
  sigma.yaml: |-
    {{ .Values.config | toYaml | nindent 4 }}
  {{- end }}
