apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configmap" .Chart.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "sigma.labels" . | nindent 4 }}
data:
  {{- if eq .Values.middleware.type "internal" }}
  config.yaml: |-
    log:
      level: debug
    database:
      type: mysql
      sqlite3:
        path: {{ .Chart.Name }}.db
      mysql:
        host: {{ .Release.Name }}-mysql
        port: {{ .Values.mysql.primary.service.ports.mysql }}
        user: {{ .Values.mysql.auth.username }}
        password: {{ .Values.mysql.auth.password }}
        dbname: sigma
      postgresql:
        host:  {{ .Release.Name }}-postgresql
        port: 5432
        user: sigma
        password: sigma
        dbname: sigma
        sslmode: disable
    redis:
      url: redis://:{{ .Values.redis.auth.password }}@{{ .Release.Name }}-redis-master:{{ .Values.redis.master.service.ports.redis }}/0
    http:
      server: 0.0.0.0:{{.Values.service.server.port}}
      worker: 0.0.0.0:{{.Values.service.worker.port}}
    daemon:
      gc:
        # if blob not associate with artifact
        retention: 72h
        # At 02:00 on Saturday
        cron: 0 2 * * 6
    storage:
      rootdirectory: ./storage
      type: s3
      filesystem:
        path: /
      s3:
        ak: {{ .Values.minio.accessKey }}
        sk: {{ .Values.minio.secretKey }}
        endpoint: http://{{ .Release.Name }}-minio:{{ .Values.minio.service.port }}
        region: cn-north-1
        {{- range .Values.minio.buckets }}
        bucket: {{ .name | quote }}
        {{end}}
        forcePathStyle: true
    proxy:
      enabled: true
      endpoint: https://registry-1.docker.io
      tlsVerify: true
      username: ""
      password: ""
    auth:
      user:
        password: ""
      internalUser:
        username: internal-sigma
        password: internal-sigma
      admin:
        username: sigma
        password: {{ randAlphaNum 8 | b64enc | trunc 8 }}
      token:
        realm: ""
        service: ""
      jwt:
        ttl: 1h
        refreshTtl: 24h
        privateKey: {{ genPrivateKey "rsa" | b64enc }}
  {{- else if eq .Values.middleware.type "external" }}
  sigma.yaml: |-
    {{ .Values.config | toYaml | nindent 4 }}
  {{- end }}