{{- if .Values.config.daemon.builder.image.push }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-post-job" ( include "sigma.fullname" . ) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "sigma.postJob.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sigma.postJob.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: check-distribution
          image: {{ printf "%s:%s" .Values.image.osShell.repository .Values.image.osShell.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/bin/bash"
            - "-c"
            - |-
              set -e;
              echo "Waiting for sigma distribution";
              wait-for-port \
                --host={{ include "sigma.distribution" . }} \
                --state=inuse \
                --timeout=120 \
                {{ .Values.service.distribution.port }};
              echo "sigma distribution is available";
      containers:
        - name: push-builder-images
          image: {{ printf "%s/%s:%s" .Values.image.registry .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sigma
          args:
            - tools
            - push-builder-images
            - --config=/etc/sigma/config.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/sigma/config.yaml
              subPath: config.yaml
              readOnly: true
          resources: {}
      volumes:
        - name: config
          configMap:
            name: {{ printf "%s-config" ( include "sigma.fullname" . ) | quote }}
{{- end }}
