apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sigma.secret" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "sigma.labels" . | nindent 4 }}
data:
  {{ $privateKey := (genPrivateKey "rsa" | b64enc) }}
  AUTH_JWT_PRIVATEKEY: {{ .Values.config.auth.jwt.privateKey | default $privateKey | quote }}
  AUTH_USER_PASSWORD: {{ (trimPrefix "sigma:" (htpasswd "sigma" (.Values.config.auth.user.password | default "sigma")))  | b64enc | quote }}
  SIGMA_DATABASE_MYSQL_PASSWORD: {{ .Values.external.mysql.password | default "" | toString | b64enc | quote }}
  SIGMA_DATABASE_POSTGRESQL_PASSWORD: {{ ternary .Values.postgresql.auth.password .Values.external.postgresql.password .Values.postgresql.enabled | default "" | toString | b64enc | quote }}
  SIGMA_REDIS_URL: {{ ternary "" .Values.external.redis.url .Values.redis.enabled | default "" | toString | b64enc | quote }}
  SIGMA_REDIS_USERNAME: {{ ternary "" .Values.external.redis.username .Values.redis.enabled | default "" | toString | b64enc | quote }}
  SIGMA_REDIS_PASSWORD: {{ ternary .Values.redis.auth.password .Values.external.redis.password .Values.redis.enabled | default "" | toString | b64enc | quote }}
  SIGMA_STORAGE_S3_AK: {{ ternary .Values.rs3.s3.ak .Values.external.s3.ak .Values.rs3.enabled | default "" | toString | b64enc | quote }}
  SIGMA_STORAGE_S3_SK: {{ ternary .Values.rs3.s3.sk .Values.external.s3.sk .Values.rs3.enabled | default "" | toString | b64enc | quote }}
  RS3_ACCESS_KEY: {{ .Values.rs3.s3.ak | default "" | toString | b64enc | quote }}
  RS3_SECRET_KEY: {{ .Values.rs3.s3.sk | default "" | toString | b64enc | quote }}
