// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-sigma/sigma/pkg/service/artifacts (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -mock_names Service=MockArtifactService -destination=artifacts_mocks.go -package=artifacts github.com/go-sigma/sigma/pkg/service/artifacts Service
//

// Package artifacts is a generated GoMock package.
package artifacts

import (
	context "context"
	reflect "reflect"

	api "github.com/go-sigma/sigma/pkg/api"
	models "github.com/go-sigma/sigma/pkg/dal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockArtifactService is a mock of Service interface.
type MockArtifactService struct {
	ctrl     *gomock.Controller
	recorder *MockArtifactServiceMockRecorder
	isgomock struct{}
}

// MockArtifactServiceMockRecorder is the mock recorder for MockArtifactService.
type MockArtifactServiceMockRecorder struct {
	mock *MockArtifactService
}

// NewMockArtifactService creates a new mock instance.
func NewMockArtifactService(ctrl *gomock.Controller) *MockArtifactService {
	mock := &MockArtifactService{ctrl: ctrl}
	mock.recorder = &MockArtifactServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArtifactService) EXPECT() *MockArtifactServiceMockRecorder {
	return m.recorder
}

// DeleteArtifact mocks base method.
func (m *MockArtifactService) DeleteArtifact(ctx context.Context, repository, digest string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArtifact", ctx, repository, digest)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArtifact indicates an expected call of DeleteArtifact.
func (mr *MockArtifactServiceMockRecorder) DeleteArtifact(ctx, repository, digest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArtifact", reflect.TypeOf((*MockArtifactService)(nil).DeleteArtifact), ctx, repository, digest)
}

// GetArtifact mocks base method.
func (m *MockArtifactService) GetArtifact(ctx context.Context, repository, digest string) (*models.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArtifact", ctx, repository, digest)
	ret0, _ := ret[0].(*models.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArtifact indicates an expected call of GetArtifact.
func (mr *MockArtifactServiceMockRecorder) GetArtifact(ctx, repository, digest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArtifact", reflect.TypeOf((*MockArtifactService)(nil).GetArtifact), ctx, repository, digest)
}

// ListArtifacts mocks base method.
func (m *MockArtifactService) ListArtifacts(ctx context.Context, req api.ListArtifactRequest) ([]*models.Artifact, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArtifacts", ctx, req)
	ret0, _ := ret[0].([]*models.Artifact)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListArtifacts indicates an expected call of ListArtifacts.
func (mr *MockArtifactServiceMockRecorder) ListArtifacts(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArtifacts", reflect.TypeOf((*MockArtifactService)(nil).ListArtifacts), ctx, req)
}
