// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-sigma/sigma/pkg/infra/cache (interfaces: Cacher)
//
// Generated by this command:
//
//	mockgen -destination=cacher_mocks.go -package=cacher github.com/go-sigma/sigma/pkg/infra/cache Cacher
//

// Package cacher is a generated GoMock package.
package cacher

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCacher is a mock of Cacher interface.
type MockCacher[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockCacherMockRecorder[T]
	isgomock struct{}
}

// MockCacherMockRecorder is the mock recorder for MockCacher.
type MockCacherMockRecorder[T any] struct {
	mock *MockCacher[T]
}

// NewMockCacher creates a new mock instance.
func NewMockCacher[T any](ctrl *gomock.Controller) *MockCacher[T] {
	mock := &MockCacher[T]{ctrl: ctrl}
	mock.recorder = &MockCacherMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacher[T]) EXPECT() *MockCacherMockRecorder[T] {
	return m.recorder
}

// Del mocks base method.
func (m *MockCacher[T]) Del(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockCacherMockRecorder[T]) Del(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockCacher[T])(nil).Del), ctx, key)
}

// Get mocks base method.
func (m *MockCacher[T]) Get(ctx context.Context, key string) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacherMockRecorder[T]) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCacher[T])(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockCacher[T]) Set(ctx context.Context, key string, val T, ttls ...time.Duration) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, val}
	for _, a := range ttls {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Set", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacherMockRecorder[T]) Set(ctx, key, val any, ttls ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, val}, ttls...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacher[T])(nil).Set), varargs...)
}
