// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-sigma/sigma/pkg/service/oauth2 (interfaces: OAuth2Service)
//
// Generated by this command:
//
//	mockgen -destination=pkg/service/oauth2/oauth2_mocks.go -package=oauth2 github.com/go-sigma/sigma/pkg/service/oauth2 OAuth2Service
//

// Package oauth2 is a generated GoMock package.
package oauth2

import (
	context "context"
	reflect "reflect"

	enums "github.com/go-sigma/sigma/pkg/api/enums"
	gomock "go.uber.org/mock/gomock"
)

// MockOAuth2Service is a mock of OAuth2Service interface.
type MockOAuth2Service struct {
	ctrl     *gomock.Controller
	recorder *MockOAuth2ServiceMockRecorder
	isgomock struct{}
}

// MockOAuth2ServiceMockRecorder is the mock recorder for MockOAuth2Service.
type MockOAuth2ServiceMockRecorder struct {
	mock *MockOAuth2Service
}

// NewMockOAuth2Service creates a new mock instance.
func NewMockOAuth2Service(ctrl *gomock.Controller) *MockOAuth2Service {
	mock := &MockOAuth2Service{ctrl: ctrl}
	mock.recorder = &MockOAuth2ServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuth2Service) EXPECT() *MockOAuth2ServiceMockRecorder {
	return m.recorder
}

// Callback mocks base method.
func (m *MockOAuth2Service) Callback(ctx context.Context, provider enums.Provider, code, endpoint, authorization string) (int64, string, string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Callback", ctx, provider, code, endpoint, authorization)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(string)
	ret4, _ := ret[4].(string)
	ret5, _ := ret[5].(error)
	return ret0, ret1, ret2, ret3, ret4, ret5
}

// Callback indicates an expected call of Callback.
func (mr *MockOAuth2ServiceMockRecorder) Callback(ctx, provider, code, endpoint, authorization any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Callback", reflect.TypeOf((*MockOAuth2Service)(nil).Callback), ctx, provider, code, endpoint, authorization)
}

// GetClientID mocks base method.
func (m *MockOAuth2Service) GetClientID(ctx context.Context, provider enums.Provider) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientID", ctx, provider)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientID indicates an expected call of GetClientID.
func (mr *MockOAuth2ServiceMockRecorder) GetClientID(ctx, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientID", reflect.TypeOf((*MockOAuth2Service)(nil).GetClientID), ctx, provider)
}
