// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-sigma/sigma/pkg/service/builders (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -mock_names Service=MockBuilderService -destination=builders_mocks.go -package=builders github.com/go-sigma/sigma/pkg/service/builders Service
//

// Package builders is a generated GoMock package.
package builders

import (
	context "context"
	io "io"
	reflect "reflect"

	api "github.com/go-sigma/sigma/pkg/api"
	enums "github.com/go-sigma/sigma/pkg/api/enums"
	models "github.com/go-sigma/sigma/pkg/dal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBuilderService is a mock of Service interface.
type MockBuilderService struct {
	ctrl     *gomock.Controller
	recorder *MockBuilderServiceMockRecorder
	isgomock struct{}
}

// MockBuilderServiceMockRecorder is the mock recorder for MockBuilderService.
type MockBuilderServiceMockRecorder struct {
	mock *MockBuilderService
}

// NewMockBuilderService creates a new mock instance.
func NewMockBuilderService(ctrl *gomock.Controller) *MockBuilderService {
	mock := &MockBuilderService{ctrl: ctrl}
	mock.recorder = &MockBuilderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuilderService) EXPECT() *MockBuilderServiceMockRecorder {
	return m.recorder
}

// CreateBuilder mocks base method.
func (m *MockBuilderService) CreateBuilder(ctx context.Context, userID string, req api.CreateBuilderRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBuilder", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBuilder indicates an expected call of CreateBuilder.
func (mr *MockBuilderServiceMockRecorder) CreateBuilder(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBuilder", reflect.TypeOf((*MockBuilderService)(nil).CreateBuilder), ctx, userID, req)
}

// GetBuilderByRepositoryID mocks base method.
func (m *MockBuilderService) GetBuilderByRepositoryID(ctx context.Context, repositoryID string) (*models.Builder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuilderByRepositoryID", ctx, repositoryID)
	ret0, _ := ret[0].(*models.Builder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBuilderByRepositoryID indicates an expected call of GetBuilderByRepositoryID.
func (mr *MockBuilderServiceMockRecorder) GetBuilderByRepositoryID(ctx, repositoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuilderByRepositoryID", reflect.TypeOf((*MockBuilderService)(nil).GetBuilderByRepositoryID), ctx, repositoryID)
}

// GetRunner mocks base method.
func (m *MockBuilderService) GetRunner(ctx context.Context, runnerID string) (*models.BuilderRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunner", ctx, runnerID)
	ret0, _ := ret[0].(*models.BuilderRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRunner indicates an expected call of GetRunner.
func (mr *MockBuilderServiceMockRecorder) GetRunner(ctx, runnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunner", reflect.TypeOf((*MockBuilderService)(nil).GetRunner), ctx, runnerID)
}

// ListRunners mocks base method.
func (m *MockBuilderService) ListRunners(ctx context.Context, builderID string, pagination api.Pagination, sort api.Sortable) ([]*models.BuilderRunner, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRunners", ctx, builderID, pagination, sort)
	ret0, _ := ret[0].([]*models.BuilderRunner)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRunners indicates an expected call of ListRunners.
func (mr *MockBuilderServiceMockRecorder) ListRunners(ctx, builderID, pagination, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRunners", reflect.TypeOf((*MockBuilderService)(nil).ListRunners), ctx, builderID, pagination, sort)
}

// RerunRunner mocks base method.
func (m *MockBuilderService) RerunRunner(ctx context.Context, req api.GetRunnerStop) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RerunRunner", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RerunRunner indicates an expected call of RerunRunner.
func (mr *MockBuilderServiceMockRecorder) RerunRunner(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RerunRunner", reflect.TypeOf((*MockBuilderService)(nil).RerunRunner), ctx, req)
}

// RunRunner mocks base method.
func (m *MockBuilderService) RunRunner(ctx context.Context, req api.PostRunnerRun) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunRunner", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunRunner indicates an expected call of RunRunner.
func (mr *MockBuilderServiceMockRecorder) RunRunner(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunRunner", reflect.TypeOf((*MockBuilderService)(nil).RunRunner), ctx, req)
}

// RunnerLogReader mocks base method.
func (m *MockBuilderService) RunnerLogReader(ctx context.Context, builderID, runnerID string, status enums.BuildStatus) (io.Reader, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunnerLogReader", ctx, builderID, runnerID, status)
	ret0, _ := ret[0].(io.Reader)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RunnerLogReader indicates an expected call of RunnerLogReader.
func (mr *MockBuilderServiceMockRecorder) RunnerLogReader(ctx, builderID, runnerID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunnerLogReader", reflect.TypeOf((*MockBuilderService)(nil).RunnerLogReader), ctx, builderID, runnerID, status)
}

// StopRunner mocks base method.
func (m *MockBuilderService) StopRunner(ctx context.Context, req api.GetRunnerStop) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopRunner", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopRunner indicates an expected call of StopRunner.
func (mr *MockBuilderServiceMockRecorder) StopRunner(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopRunner", reflect.TypeOf((*MockBuilderService)(nil).StopRunner), ctx, req)
}

// UpdateBuilder mocks base method.
func (m *MockBuilderService) UpdateBuilder(ctx context.Context, userID, builderID string, req api.UpdateBuilderRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBuilder", ctx, userID, builderID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBuilder indicates an expected call of UpdateBuilder.
func (mr *MockBuilderServiceMockRecorder) UpdateBuilder(ctx, userID, builderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBuilder", reflect.TypeOf((*MockBuilderService)(nil).UpdateBuilder), ctx, userID, builderID, req)
}
