// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-sigma/sigma/pkg/distribution/clients (interfaces: Clients,ClientsFactory)
//
// Generated by this command:
//
//	mockgen -destination=clients_mocks.go -package=clients github.com/go-sigma/sigma/pkg/distribution/clients Clients,ClientsFactory
//

// Package clients is a generated GoMock package.
package clients

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	distribution "github.com/distribution/distribution/v3"
	config "github.com/go-sigma/sigma/pkg/config"
	digest "github.com/opencontainers/go-digest"
	gomock "go.uber.org/mock/gomock"
)

// MockClients is a mock of Clients interface.
type MockClients struct {
	ctrl     *gomock.Controller
	recorder *MockClientsMockRecorder
	isgomock struct{}
}

// MockClientsMockRecorder is the mock recorder for MockClients.
type MockClientsMockRecorder struct {
	mock *MockClients
}

// NewMockClients creates a new mock instance.
func NewMockClients(ctrl *gomock.Controller) *MockClients {
	mock := &MockClients{ctrl: ctrl}
	mock.recorder = &MockClientsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClients) EXPECT() *MockClientsMockRecorder {
	return m.recorder
}

// AuthToken mocks base method.
func (m *MockClients) AuthToken() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthToken")
	ret0, _ := ret[0].(error)
	return ret0
}

// AuthToken indicates an expected call of AuthToken.
func (mr *MockClientsMockRecorder) AuthToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthToken", reflect.TypeOf((*MockClients)(nil).AuthToken))
}

// DoRequest mocks base method.
func (m *MockClients) DoRequest(ctx context.Context, method, path string, headers http.Header, bodyReaders ...io.Reader) (int, http.Header, io.ReadCloser, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, method, path, headers}
	for _, a := range bodyReaders {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DoRequest", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(http.Header)
	ret2, _ := ret[2].(io.ReadCloser)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// DoRequest indicates an expected call of DoRequest.
func (mr *MockClientsMockRecorder) DoRequest(ctx, method, path, headers any, bodyReaders ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, method, path, headers}, bodyReaders...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoRequest", reflect.TypeOf((*MockClients)(nil).DoRequest), varargs...)
}

// GetBlob mocks base method.
func (m *MockClients) GetBlob(ctx context.Context, repository string, arg2 digest.Digest) (distribution.Descriptor, io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlob", ctx, repository, arg2)
	ret0, _ := ret[0].(distribution.Descriptor)
	ret1, _ := ret[1].(io.ReadCloser)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBlob indicates an expected call of GetBlob.
func (mr *MockClientsMockRecorder) GetBlob(ctx, repository, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlob", reflect.TypeOf((*MockClients)(nil).GetBlob), ctx, repository, arg2)
}

// GetManifest mocks base method.
func (m *MockClients) GetManifest(ctx context.Context, repository, reference string) (distribution.Manifest, distribution.Descriptor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManifest", ctx, repository, reference)
	ret0, _ := ret[0].(distribution.Manifest)
	ret1, _ := ret[1].(distribution.Descriptor)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetManifest indicates an expected call of GetManifest.
func (mr *MockClientsMockRecorder) GetManifest(ctx, repository, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManifest", reflect.TypeOf((*MockClients)(nil).GetManifest), ctx, repository, reference)
}

// HeadBlob mocks base method.
func (m *MockClients) HeadBlob(ctx context.Context, repository string, arg2 digest.Digest) (distribution.Descriptor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadBlob", ctx, repository, arg2)
	ret0, _ := ret[0].(distribution.Descriptor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadBlob indicates an expected call of HeadBlob.
func (mr *MockClientsMockRecorder) HeadBlob(ctx, repository, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadBlob", reflect.TypeOf((*MockClients)(nil).HeadBlob), ctx, repository, arg2)
}

// HeadManifest mocks base method.
func (m *MockClients) HeadManifest(ctx context.Context, repository, reference string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeadManifest", ctx, repository, reference)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeadManifest indicates an expected call of HeadManifest.
func (mr *MockClientsMockRecorder) HeadManifest(ctx, repository, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeadManifest", reflect.TypeOf((*MockClients)(nil).HeadManifest), ctx, repository, reference)
}

// PutBlob mocks base method.
func (m *MockClients) PutBlob(ctx context.Context, repository string, arg2 digest.Digest, content io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutBlob", ctx, repository, arg2, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutBlob indicates an expected call of PutBlob.
func (mr *MockClientsMockRecorder) PutBlob(ctx, repository, arg2, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutBlob", reflect.TypeOf((*MockClients)(nil).PutBlob), ctx, repository, arg2, content)
}

// MockClientsFactory is a mock of ClientsFactory interface.
type MockClientsFactory struct {
	ctrl     *gomock.Controller
	recorder *MockClientsFactoryMockRecorder
	isgomock struct{}
}

// MockClientsFactoryMockRecorder is the mock recorder for MockClientsFactory.
type MockClientsFactoryMockRecorder struct {
	mock *MockClientsFactory
}

// NewMockClientsFactory creates a new mock instance.
func NewMockClientsFactory(ctrl *gomock.Controller) *MockClientsFactory {
	mock := &MockClientsFactory{ctrl: ctrl}
	mock.recorder = &MockClientsFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientsFactory) EXPECT() *MockClientsFactoryMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockClientsFactory) New(arg0 *config.Configuration) (Clients, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", arg0)
	ret0, _ := ret[0].(Clients)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockClientsFactoryMockRecorder) New(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockClientsFactory)(nil).New), arg0)
}
