// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-sigma/sigma/pkg/dal/repository/registry (interfaces: BlobRepository)
//
// Generated by this command:
//
//	mockgen -destination=blob_mocks.go -package=registry github.com/go-sigma/sigma/pkg/dal/repository/registry BlobRepository
//

// Package registry is a generated GoMock package.
package registry

import (
	context "context"
	reflect "reflect"

	models "github.com/go-sigma/sigma/pkg/dal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBlobRepository is a mock of BlobRepository interface.
type MockBlobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBlobRepositoryMockRecorder
	isgomock struct{}
}

// MockBlobRepositoryMockRecorder is the mock recorder for MockBlobRepository.
type MockBlobRepositoryMockRecorder struct {
	mock *MockBlobRepository
}

// NewMockBlobRepository creates a new mock instance.
func NewMockBlobRepository(ctrl *gomock.Controller) *MockBlobRepository {
	mock := &MockBlobRepository{ctrl: ctrl}
	mock.recorder = &MockBlobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlobRepository) EXPECT() *MockBlobRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBlobRepository) Create(ctx context.Context, blob *models.Blob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, blob)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBlobRepositoryMockRecorder) Create(ctx, blob any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBlobRepository)(nil).Create), ctx, blob)
}

// DeleteByID mocks base method.
func (m *MockBlobRepository) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockBlobRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockBlobRepository)(nil).DeleteByID), ctx, id)
}

// Exists mocks base method.
func (m *MockBlobRepository) Exists(ctx context.Context, digest string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, digest)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockBlobRepositoryMockRecorder) Exists(ctx, digest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockBlobRepository)(nil).Exists), ctx, digest)
}

// FindAssociateWithArtifact mocks base method.
func (m *MockBlobRepository) FindAssociateWithArtifact(ctx context.Context, ids []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAssociateWithArtifact", ctx, ids)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAssociateWithArtifact indicates an expected call of FindAssociateWithArtifact.
func (mr *MockBlobRepositoryMockRecorder) FindAssociateWithArtifact(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAssociateWithArtifact", reflect.TypeOf((*MockBlobRepository)(nil).FindAssociateWithArtifact), ctx, ids)
}

// FindByDigest mocks base method.
func (m *MockBlobRepository) FindByDigest(ctx context.Context, digest string) (*models.Blob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDigest", ctx, digest)
	ret0, _ := ret[0].(*models.Blob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDigest indicates an expected call of FindByDigest.
func (mr *MockBlobRepositoryMockRecorder) FindByDigest(ctx, digest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDigest", reflect.TypeOf((*MockBlobRepository)(nil).FindByDigest), ctx, digest)
}

// FindByDigests mocks base method.
func (m *MockBlobRepository) FindByDigests(ctx context.Context, digests []string) ([]*models.Blob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDigests", ctx, digests)
	ret0, _ := ret[0].([]*models.Blob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDigests indicates an expected call of FindByDigests.
func (mr *MockBlobRepositoryMockRecorder) FindByDigests(ctx, digests any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDigests", reflect.TypeOf((*MockBlobRepository)(nil).FindByDigests), ctx, digests)
}

// FindDeletableWithCursor mocks base method.
func (m *MockBlobRepository) FindDeletableWithCursor(ctx context.Context, before int64, last string, limit int64) ([]*models.Blob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDeletableWithCursor", ctx, before, last, limit)
	ret0, _ := ret[0].([]*models.Blob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDeletableWithCursor indicates an expected call of FindDeletableWithCursor.
func (mr *MockBlobRepositoryMockRecorder) FindDeletableWithCursor(ctx, before, last, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDeletableWithCursor", reflect.TypeOf((*MockBlobRepository)(nil).FindDeletableWithCursor), ctx, before, last, limit)
}

// FindWithLastPull mocks base method.
func (m *MockBlobRepository) FindWithLastPull(ctx context.Context, before int64, last string, limit int64) ([]*models.Blob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithLastPull", ctx, before, last, limit)
	ret0, _ := ret[0].([]*models.Blob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWithLastPull indicates an expected call of FindWithLastPull.
func (mr *MockBlobRepositoryMockRecorder) FindWithLastPull(ctx, before, last, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithLastPull", reflect.TypeOf((*MockBlobRepository)(nil).FindWithLastPull), ctx, before, last, limit)
}

// Incr mocks base method.
func (m *MockBlobRepository) Incr(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Incr", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Incr indicates an expected call of Incr.
func (mr *MockBlobRepositoryMockRecorder) Incr(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Incr", reflect.TypeOf((*MockBlobRepository)(nil).Incr), ctx, id)
}

// UploadCreate mocks base method.
func (m *MockBlobRepository) UploadCreate(ctx context.Context, blobUpload *models.BlobUpload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadCreate", ctx, blobUpload)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadCreate indicates an expected call of UploadCreate.
func (mr *MockBlobRepositoryMockRecorder) UploadCreate(ctx, blobUpload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadCreate", reflect.TypeOf((*MockBlobRepository)(nil).UploadCreate), ctx, blobUpload)
}

// UploadDeleteByUploadID mocks base method.
func (m *MockBlobRepository) UploadDeleteByUploadID(ctx context.Context, uploadID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadDeleteByUploadID", ctx, uploadID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadDeleteByUploadID indicates an expected call of UploadDeleteByUploadID.
func (mr *MockBlobRepositoryMockRecorder) UploadDeleteByUploadID(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadDeleteByUploadID", reflect.TypeOf((*MockBlobRepository)(nil).UploadDeleteByUploadID), ctx, uploadID)
}

// UploadFindAllByUploadID mocks base method.
func (m *MockBlobRepository) UploadFindAllByUploadID(ctx context.Context, uploadID string) ([]*models.BlobUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFindAllByUploadID", ctx, uploadID)
	ret0, _ := ret[0].([]*models.BlobUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFindAllByUploadID indicates an expected call of UploadFindAllByUploadID.
func (mr *MockBlobRepositoryMockRecorder) UploadFindAllByUploadID(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFindAllByUploadID", reflect.TypeOf((*MockBlobRepository)(nil).UploadFindAllByUploadID), ctx, uploadID)
}

// UploadGetLastPart mocks base method.
func (m *MockBlobRepository) UploadGetLastPart(ctx context.Context, uploadID string) (*models.BlobUpload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadGetLastPart", ctx, uploadID)
	ret0, _ := ret[0].(*models.BlobUpload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadGetLastPart indicates an expected call of UploadGetLastPart.
func (mr *MockBlobRepositoryMockRecorder) UploadGetLastPart(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadGetLastPart", reflect.TypeOf((*MockBlobRepository)(nil).UploadGetLastPart), ctx, uploadID)
}

// UploadTotalEtagsByUploadID mocks base method.
func (m *MockBlobRepository) UploadTotalEtagsByUploadID(ctx context.Context, uploadID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadTotalEtagsByUploadID", ctx, uploadID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadTotalEtagsByUploadID indicates an expected call of UploadTotalEtagsByUploadID.
func (mr *MockBlobRepositoryMockRecorder) UploadTotalEtagsByUploadID(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadTotalEtagsByUploadID", reflect.TypeOf((*MockBlobRepository)(nil).UploadTotalEtagsByUploadID), ctx, uploadID)
}

// UploadTotalSizeByUploadID mocks base method.
func (m *MockBlobRepository) UploadTotalSizeByUploadID(ctx context.Context, uploadID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadTotalSizeByUploadID", ctx, uploadID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadTotalSizeByUploadID indicates an expected call of UploadTotalSizeByUploadID.
func (mr *MockBlobRepositoryMockRecorder) UploadTotalSizeByUploadID(ctx, uploadID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadTotalSizeByUploadID", reflect.TypeOf((*MockBlobRepository)(nil).UploadTotalSizeByUploadID), ctx, uploadID)
}
