{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sigma.distribution" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "sigma.distribution.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      {{- include "sigma.distribution.labels" . | nindent 6 }}
{{- end }}
