apiVersion: v1
kind: Service
metadata:
  name: {{ include "sigma.distribution" . }}
  labels:
    {{- include "sigma.distribution.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.distribution.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sigma.distribution.labels" . | nindent 4 }}
