// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-sigma/sigma/pkg/dal/dao (interfaces: AuditService,AuditServiceFactory)
//
// Generated by this command:
//
//	mockgen -destination=audit_mocks.go -package=dao github.com/go-sigma/sigma/pkg/dal/dao AuditService,AuditServiceFactory
//

// Package dao is a generated GoMock package.
package dao

import (
	context "context"
	reflect "reflect"

	models "github.com/go-sigma/sigma/pkg/dal/models"
	query "github.com/go-sigma/sigma/pkg/dal/query"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditService is a mock of AuditService interface.
type MockAuditService struct {
	ctrl     *gomock.Controller
	recorder *MockAuditServiceMockRecorder
	isgomock struct{}
}

// MockAuditServiceMockRecorder is the mock recorder for MockAuditService.
type MockAuditServiceMockRecorder struct {
	mock *MockAuditService
}

// NewMockAuditService creates a new mock instance.
func NewMockAuditService(ctrl *gomock.Controller) *MockAuditService {
	mock := &MockAuditService{ctrl: ctrl}
	mock.recorder = &MockAuditServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditService) EXPECT() *MockAuditServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuditService) Create(ctx context.Context, audit *models.Audit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, audit)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAuditServiceMockRecorder) Create(ctx, audit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuditService)(nil).Create), ctx, audit)
}

// HotNamespace mocks base method.
func (m *MockAuditService) HotNamespace(ctx context.Context, userID int64, top int) ([]*models.Namespace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HotNamespace", ctx, userID, top)
	ret0, _ := ret[0].([]*models.Namespace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HotNamespace indicates an expected call of HotNamespace.
func (mr *MockAuditServiceMockRecorder) HotNamespace(ctx, userID, top any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HotNamespace", reflect.TypeOf((*MockAuditService)(nil).HotNamespace), ctx, userID, top)
}

// MockAuditServiceFactory is a mock of AuditServiceFactory interface.
type MockAuditServiceFactory struct {
	ctrl     *gomock.Controller
	recorder *MockAuditServiceFactoryMockRecorder
	isgomock struct{}
}

// MockAuditServiceFactoryMockRecorder is the mock recorder for MockAuditServiceFactory.
type MockAuditServiceFactoryMockRecorder struct {
	mock *MockAuditServiceFactory
}

// NewMockAuditServiceFactory creates a new mock instance.
func NewMockAuditServiceFactory(ctrl *gomock.Controller) *MockAuditServiceFactory {
	mock := &MockAuditServiceFactory{ctrl: ctrl}
	mock.recorder = &MockAuditServiceFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditServiceFactory) EXPECT() *MockAuditServiceFactoryMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockAuditServiceFactory) New(txs ...*query.Query) AuditService {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range txs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "New", varargs...)
	ret0, _ := ret[0].(AuditService)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockAuditServiceFactoryMockRecorder) New(txs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockAuditServiceFactory)(nil).New), txs...)
}
