name: E2E CI

on:
  push:
    branches:
      - main
      - gh-readonly-queue/main/*
  pull_request:
    branches:
      - main

jobs:
  e2e-test:
    name: e2e-test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: Build latest skopeo
        run: |
          git clone --depth 1 --branch v1.15.0 https://github.com/containers/skopeo.git
          cd skopeo
          DISABLE_CGO=1 make bin/skopeo
          sudo cp ./bin/skopeo /usr/bin/skopeo
          cd ..
          rm -rf skopeo
          skopeo --version
      - name: Build
        run: |
          IP=`hostname -I | awk '{print $1}'`
          echo '{"insecure-registries" : ["'$IP':3000"]}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
          echo $DOCKER_HOST

          docker buildx create --use
          make docker-build-builder-local dockerfile-local
          docker buildx build -f build/Dockerfile --build-arg WITH_TRIVY_DB=true --platform linux/amd64 --progress plain --output type=docker,dest=- -t sigma:latest . | docker load
      - name: Run sigma
        run: |
          docker run --name sigma -v /var/run/docker.sock:/var/run/docker.sock -d -p 3000:3000 sigma:latest
          sleep 5
          docker logs sigma
      - name: Test push and e2e with k6
        run: |
          ./e2e/push.sh
          curl https://github.com/grafana/k6/releases/download/v0.46.0/k6-v0.46.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1
          ./k6 run e2e/sc.js
