name: Image CI

on:
  push:
    branches:
      - main
      - gh-readonly-queue/main/*
  pull_request:
    branches:
      - main

jobs:
  image-build:
    name: image-build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: tosone
      #     password: ${{ secrets.GHCR_TOKEN }}
      # - name: Cache Docker layers
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/Dockerfile
          platforms: linux/amd64
          push: false
          tags: ghcr.io/ximager/ximager:latest
          provenance: false
          sbom: false
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      # - name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache
