name: Lint CI

on:
  push:
    branches:
      - main
      - gh-readonly-queue/main/*
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go: ["1.23"]
        node: ["20"]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: corepack enable
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          cache-dependency-path: "web/yarn.lock"
      - name: Build web
        run: |
          cd web
          yarn install --immutable
          yarn build
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.60.1
          args: --timeout=30m --verbose --build-tags "timetzdata,exclude_graphdriver_devicemapper,exclude_graphdriver_btrfs,containers_image_openpgp"
          skip-pkg-cache: true
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./build/Dockerfile
          ignore: DL3018,DL3003,SC2155
