name: Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: ["1.19"]
        node: ["18"]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ximager
          MYSQL_DATABASE: ximager
          MYSQL_USER: ximager
          MYSQL_PASSWORD: ximager
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          cache-dependency-path: "web/yarn.lock"
      - name: Test
        run: |
          cd web
          yarn install --frozen-lockfile
          yarn build
